import { COMPANION_TABLES } from "./rules/companion-tables.mjs";
import { familiarDead } from "./familiars.mjs";

/**
 * Skills & Powers animal companions and mounts (Animal Master (POSP), Rider (POSP); tables and rules in
 * module/rules/companion-tables.mjs, GENERATED by tools/build-hireling-data.py; the creatures are actors in the
 * Hirelings & Mounts compendium, folder "Animal Companions & Mounts (POSP)").
 *  - Animal Master: one companion (Table 42, d20), bonded "similar to a wizard's familiar". Lost "through carelessness":
 *    -10% of the current experience and no companion of that species again; a natural death costs nothing.
 *  - Rider: one bonded mount (Table 43: d6 for the group, d8 for the mount). "Each will know the general state of health of
 *    the other, the direction the other is in, and the distance": shown on the sheet (distance and direction when both
 *    tokens are on the viewed scene). Its death: 2d6 damage to the rider; by negligence also a saving throw vs. spells or
 *    feeblemind for 2d6 hours (a chat note). Neglect may make it flee: no empathic rapport with an animal again.
 *  - Cavalier and Noble "must purchase a mount": a warning while the character owns no mount.
 * Character data: `system.bond` { companion, mount (actor UUIDs, also in `system.animals.actors`), barred (species:
 * actor identifiers), rapportLost }. Owner's rulings: generated stat blocks, bond with GM buttons, mount warning.
 */
export const COMPANIONS = COMPANION_TABLES;
export const BOND_KITS = { companion: "animal-master-posp", mount: "rider-posp" };
export const PACK = "ad2e.hirelings";

const resolve = uuid => (uuid ? (foundry.utils.fromUuidSync ?? globalThis.fromUuidSync)?.(uuid, { strict: false }) ?? null : null);

/** The character's kit identifier (a fitting kit), or "". */
function kitId(character) {
  const info = character?.system?.classInfo;
  return info?.kitFits ? (info.kitItem?.system.identifier ?? "") : "";
}

/** Which bond the character's kit gives: "companion", "mount" or "". */
export function bondKind(character) {
  const kit = kitId(character);
  return Object.entries(BOND_KITS).find(([, id]) => id === kit)?.[0] ?? "";
}

/** Whether the kit requires owning a mount (Cavalier, Noble). */
export function needsMount(character) {
  const kit = kitId(character);
  return kit === COMPANIONS.rules.cavalier || kit === COMPANIONS.rules.noble;
}

/** The species key of an animal actor (its identifier, else its name). */
export function speciesOf(actor) {
  return actor?.system?.identifier || actor?.name || "";
}

/** 8-point compass direction from a to b on a canvas (y grows downwards); "" at the same point. */
export function compass(dx, dy) {
  if (!dx && !dy) return "";
  const deg = (Math.atan2(dx, -dy) * 180 / Math.PI + 360) % 360;
  return ["N", "NE", "E", "SE", "S", "SW", "W", "NW"][Math.round(deg / 45) % 8];
}

/** Health text of an animal: "hp / max" and its state. */
function health(actor) {
  const hp = actor.system.hp ?? {};
  return { value: hp.value ?? 0, max: hp.max ?? 0, dead: familiarDead(actor) };
}

/** Distance (scene units) and direction between the first tokens of two actors on a scene, or null. */
export function tokenBearing(a, b, scene = globalThis.canvas?.scene, measure = null) {
  if (!scene || !a || !b) return null;
  const tokenOf = actor => scene.tokens?.find(t => t.actorId === actor.id || t.actor?.id === actor.id) ?? null;
  const ta = tokenOf(a);
  const tb = tokenOf(b);
  if (!ta || !tb) return null;
  const grid = scene.grid?.size || 100;
  const ca = { x: ta.x + (ta.width ?? 1) * grid / 2, y: ta.y + (ta.height ?? 1) * grid / 2 };
  const cb = { x: tb.x + (tb.width ?? 1) * grid / 2, y: tb.y + (tb.height ?? 1) * grid / 2 };
  const dist = measure ? measure(ca, cb)
    : (globalThis.canvas?.grid?.measurePath?.([ca, cb])?.distance ?? Math.hypot(cb.x - ca.x, cb.y - ca.y) / grid * (scene.grid?.distance ?? 5));
  return { distance: Math.round(dist), units: scene.grid?.units ?? "ft", direction: compass(cb.x - ca.x, cb.y - ca.y) };
}

/** Display state of a character's bonds. */
export function bondInfo(character) {
  const sys = character.system;
  const bond = sys.bond ?? {};
  const kind = bondKind(character);
  const row = uuid => {
    const actor = resolve(uuid);
    if (!uuid) return null;
    if (!actor?.system) return { uuid, missing: true };
    return { uuid, actor, name: actor.name, img: actor.img, ...health(actor) };
  };
  const companion = row(bond.companion);
  if (companion?.actor) companion.oversize = oversizeCompanion(companion.actor);
  const mount = row(bond.mount);
  if (mount?.actor) mount.bearing = tokenBearing(character, mount.actor);
  const ownsMount = (sys.animals?.actors ?? []).some(u => resolve(u)?.system?.role === "mount");
  return { kind, companion, mount, barred: [...(bond.barred ?? [])], rapportLost: !!bond.rapportLost,
    mountNeeded: needsMount(character) && !ownsMount };
}

/**
 * "All animal companions should be size S (small)" (Animal Master (POSP)): true for a companion larger than S (owner's
 * ruling: a warning only; T, S, or no size given pass). The size is the first letter of the stat block's size.
 */
export function oversizeCompanion(animal) {
  const letter = String(animal?.system?.size ?? "").trim().charAt(0).toUpperCase();
  return ["M", "L", "H", "G"].includes(letter);
}

/** Whether an animal may become the character's companion or mount, or the reason it may not. */
export function canBond(character, animal, kind) {
  const bond = character.system.bond ?? {};
  if (!kind || bondKind(character) !== kind) return "kit";
  if (kind === "companion" && (bond.barred ?? []).includes(speciesOf(animal))) return "barred";
  if (kind === "mount" && bond.rapportLost) return "rapport";
  if (bond[kind] && bond[kind] !== animal.uuid && resolve(bond[kind])?.system && !familiarDead(resolve(bond[kind]))) return "hasOne";
  return "";
}

/** Experience after losing a companion carelessly: 10% of the current total (every class of a multi-class character). */
export function carelessXp(xp, percent = COMPANIONS.rules.carelessLoss.xpPercent) {
  return Math.max(xp - Math.floor(xp * percent / 100), 0);
}

/**
 * Roll a table row: companions (d20) or mounts (d6 group, d8 mount; or, with a homeland, one of that homeland's Table 43
 * entries with equal chance, owner's choice). `die(n)` is injectable.
 */
export function rollBondTable(kind, die = n => Math.ceil(Math.random() * n), homeland = "any") {
  if (kind === "mount" && homeland && homeland !== "any" && COMPANIONS.homelands?.[homeland]) {
    const list = COMPANIONS.homelands[homeland];
    const roll = die(list.length);
    return { kind, homeland, rolls: [roll], row: list[roll - 1] };
  }
  if (kind === "companion") {
    const roll = die(20);
    return { kind, rolls: [roll], row: COMPANIONS.companions.find(r => r.roll === roll) };
  }
  const g = die(6);
  const group = COMPANIONS.rules.mountGroups.find(x => g >= x.min && g <= x.max).group;
  const roll = die(8);
  return { kind, group, rolls: [g, roll], row: COMPANIONS.mounts[group].find(r => r.roll === roll) };
}

const esc = v => foundry.utils.escapeHTML?.(String(v ?? "")) ?? String(v ?? "");
const i18n = (k, d) => (d ? game.i18n.format(k, d) : game.i18n.localize(k));
const speaker = actor => ChatMessage.getSpeaker({ actor });

/** GM: roll Table 42 or 43 and post the result with links to the creatures in the compendium. */
export async function rollBondCreature(character, kind, homeland = "any") {
  const r = rollBondTable(kind, undefined, homeland);
  const links = r.row.actors.map(a => `@UUID[Compendium.${PACK}.Actor.${a.id}]{${esc(r.row.name)}}`).join(" / ");
  const group = r.homeland ? ` (${i18n(`AD2E.Bond.Homeland.${r.homeland}`)}, d${COMPANIONS.homelands[r.homeland].length})`
    : (r.group ? ` (${i18n(`AD2E.Bond.Group.${r.group}`)}, d6 ${r.rolls[0]})` : "");
  return ChatMessage.create({ speaker: speaker(character), whisper: ChatMessage.getWhisperRecipients?.("GM") ?? [],
    content: `<p><strong>${esc(i18n(kind === "companion" ? "AD2E.Bond.CompanionTable" : "AD2E.Bond.MountTable"))}</strong>${esc(group)}: `
      + `${r.rolls.at(-1)} — ${links}</p><p class="ad2e-note">${esc(i18n("AD2E.Bond.DragHint"))}</p>` });
}

/** Bond an animal (already in the character's animal list) as companion or mount. */
export async function setBond(character, animal, kind) {
  const why = canBond(character, animal, kind);
  if (why) {
    ui.notifications.warn(i18n(`AD2E.Bond.Refused.${why}`, { name: animal.name }));
    return false;
  }
  await character.update({ [`system.bond.${kind}`]: animal.uuid });
  if (kind === "companion" && oversizeCompanion(animal)) ui.notifications.warn(i18n("AD2E.Bond.Oversize", { name: animal.name, size: animal.system.size }));
  return true;
}

/** GM: the companion is lost. Careless: -10% experience and the species barred; otherwise no penalty. */
export async function companionLost(character, careless) {
  const info = bondInfo(character);
  if (!info.companion) return null;
  const update = { "system.bond.companion": "" };
  let text = i18n("AD2E.Bond.CompanionGone", { name: character.name, animal: info.companion.name ?? "" });
  if (careless) {
    const sys = character.system;
    update["system.xp"] = carelessXp(sys.xp ?? 0);
    if (sys.multi) update["system.multiClass.classes"] = sys.multi.classes.filter(c => !c.primary)
      .map(c => ({ identifier: c.identifier, level: c.level, xp: carelessXp(c.xp ?? 0) }));
    const species = info.companion.actor ? speciesOf(info.companion.actor) : "";
    if (species) update["system.bond.barred"] = [...new Set([...(character.system.bond?.barred ?? []), species])];
    text += " " + i18n("AD2E.Bond.Careless", { xp: (sys.xp ?? 0) - update["system.xp"], name: info.companion.name ?? "" });
  }
  await character.update(update);
  return ChatMessage.create({ speaker: speaker(character), content: `<p>${esc(text)}</p>` });
}

/** GM: the bonded mount died: 2d6 damage to the rider; by negligence also a save vs. spells (feeblemind for 2d6 hours on a failure). */
export async function mountDied(character, negligent) {
  const info = bondInfo(character);
  const name = info.mount?.name ?? "";
  const dmg = await new Roll(COMPANIONS.rules.mountDeath).evaluate();
  await character.update({ "system.bond.mount": "" });
  await character.applyDamage?.(dmg.total, { single: true });
  let note = "";
  if (negligent) {
    const hours = await new Roll(COMPANIONS.rules.negligence.hours).evaluate();
    note = ` ${i18n("AD2E.Bond.Negligent", { hours: hours.total })}`;
  }
  await ChatMessage.create({ speaker: speaker(character), rolls: [dmg],
    content: `<p>${esc(i18n("AD2E.Bond.MountDied", { name: character.name, mount: name, damage: dmg.total }) + note)}</p>` });
  if (negligent) return character.rollSave?.(COMPANIONS.rules.negligence.save);
  return null;
}

/** GM: the mount fled from neglect: no empathic rapport with an animal again. */
export async function mountFled(character) {
  const name = bondInfo(character).mount?.name ?? "";
  await character.update({ "system.bond.mount": "", "system.bond.rapportLost": true });
  return ChatMessage.create({ speaker: speaker(character), content: `<p>${esc(i18n("AD2E.Bond.Fled", { name: character.name, mount: name }))}</p>` });
}

/** The active GM is told when a bonded mount or companion dies (the GM then uses the sheet's buttons). */
export function registerCompanions() {
  Hooks.on("updateActor", (actor, changes) => {
    if (!game.user?.isActiveGM || actor.type !== "monster" || changes?.system?.hp?.value === undefined || !familiarDead(actor)) return;
    for (const character of game.actors?.filter(a => a.type === "character") ?? []) {
      const bond = character.system.bond ?? {};
      const kind = bond.mount === actor.uuid ? "mount" : (bond.companion === actor.uuid ? "companion" : "");
      if (!kind) continue;
      ChatMessage.create({ whisper: ChatMessage.getWhisperRecipients?.("GM") ?? [], speaker: speaker(character),
        content: `<p>${esc(i18n(`AD2E.Bond.DeathNotice.${kind}`, { name: character.name, animal: actor.name }))}</p>` });
    }
  });
}
