import { ABILITY_TABLES } from "./rules/ability-tables.mjs";
import { HIT_DICE, SAVE_TABLE, SPECIALIST_ATTACKS, THAC0_TABLE, WARRIOR_ATTACKS, XP_RESTART, XP_TABLE } from "./rules/level-tables.mjs";
import { PROFICIENCY_GROUPS, PROFICIENCY_SLOTS } from "./rules/proficiency-tables.mjs";
import { CON_SAVE_BONUS } from "./rules/race-tables.mjs";
import { CREATURE_THAC0 } from "./rules/monster-tables.mjs";
import { SPELL_PROGRESSION } from "./rules/spell-tables.mjs";
import { CLASS_TABLES } from "./rules/class-tables.mjs";
import { TREASURE_TABLES } from "./rules/treasure-tables.mjs";
import { ENCOUNTER_TABLES } from "./rules/encounter-tables.mjs";
import { BASE_MOVEMENT, COIN_VALUES, COINS_PER_POUND, ENCUMBRANCE_TABLE, MOVEMENT_TABLE } from "./rules/movement-tables.mjs";

/**
 * Rules data for AD&D 2e. Numeric tables only; verify against an owned copy of the
 * rulebooks before play. Edit here; nothing else hard-codes these numbers.
 */

export const AD2E = {};

AD2E.abilities = ["str", "dex", "con", "int", "wis", "cha"];
AD2E.abilityLabels = Object.fromEntries(AD2E.abilities.map(k => [k, `AD2E.Ability.${k}`]));

AD2E.alignments = {
  lg: "AD2E.Alignment.lg", ng: "AD2E.Alignment.ng", cg: "AD2E.Alignment.cg",
  ln: "AD2E.Alignment.ln", n: "AD2E.Alignment.n", cn: "AD2E.Alignment.cn",
  le: "AD2E.Alignment.le", ne: "AD2E.Alignment.ne", ce: "AD2E.Alignment.ce"
};

AD2E.classGroups = {
  warrior: "AD2E.Group.warrior",
  wizard: "AD2E.Group.wizard",
  priest: "AD2E.Group.priest",
  rogue: "AD2E.Group.rogue"
};

AD2E.saves = ["par", "rsw", "pet", "br", "sp"];

/** Return the row whose [min, max] contains value (clamped to the table ends). */
export function lookup(table, value) {
  return table.find(r => value >= r.min && value <= r.max)
    ?? (value < table[0].min ? table[0] : table.at(-1));
}

/**
 * Ability tables (PHB Tables 1-6) generated from the AD&D 2e fandom wiki by
 * tools/build-ability-tables.py. Rows are { min, max, ...columns } keyed by score;
 * strExceptional is keyed by the 18/xx percentile (100 = 18/00).
 */
AD2E.abilityTables = ABILITY_TABLES;

/**
 * Table-driven ability tests. The target is the named column of the ability's current
 * row; the test succeeds when the roll is <= target. `failsOnSuccess` marks tests where
 * rolling under the target means the bad outcome (e.g. Wisdom spell failure); `outcomes`
 * overrides the Success/Failure chat labels.
 */
AD2E.abilityTests = {
  openDoors:    { ability: "str", die: "1d20",  field: "openDoors" },
  openLocked:   { ability: "str", die: "1d20",  field: "openLocked" },
  bendBars:     { ability: "str", die: "1d100", field: "bendBars" },
  systemShock:  { ability: "con", die: "1d100", field: "systemShock" },
  resurrection: { ability: "con", die: "1d100", field: "resurrection" },
  learnSpell:   { ability: "int", die: "1d100", field: "learnSpell" },
  spellFailure: { ability: "wis", die: "1d100", field: "spellFailure", failsOnSuccess: true,
                  outcomes: { success: "AD2E.Test.SpellWorks", failure: "AD2E.Test.SpellFails" } }
};

/**
 * Saving throws (PHB Table 60), hit dice and XP (PHB Tables 14/20/23/25), generated by
 * tools/build-level-tables.py. Hit dice stop at level 9 (warrior, priest) or 10 (wizard,
 * rogue); after that a fixed bonus per level applies and CON no longer adds hit points.
 */
AD2E.saveTable = SAVE_TABLE;
AD2E.hitDice = HIT_DICE;
AD2E.xpTable = XP_TABLE;
/** First level whose XP counts from a restart (druid 17: hierophant druids keep 1 XP and advance anew). */
AD2E.xpRestart = XP_RESTART;

/**
 * Hit dice and fixed bonus HP for a group at a level. Levels past the table (20) continue
 * the last row's per-level bonus.
 */
export function hitDiceAt(group, level) {
  const { die, levels } = AD2E.hitDice[group];
  const last = levels.at(-1);
  if (level <= last.level) return { die, ...levels[Math.max(level, 1) - 1] };
  const perLevel = last.bonus - levels.at(-2).bonus;
  return { die, level, dice: last.dice, bonus: last.bonus + perLevel * (level - last.level) };
}

/**
 * PHB Table 9: racial Constitution saving-throw bonus (dwarf, gnome, halfling), generated by
 * tools/build-race-data.py. Scores below the first row (4) give no bonus.
 */
AD2E.conSaveBonus = CON_SAVE_BONUS;

export function conSaveBonus(con) {
  return con < AD2E.conSaveBonus[0].min ? 0 : lookup(AD2E.conSaveBonus, con).bonus;
}

/**
 * THAC0: PHB Table 53 for levels 1-20 (generated); past level 20 the progression below continues it
 * (tools/build-level-tables.py asserts it reproduces Table 53). THAC0 = 20 - floor((level-1)/divisor)*step.
 */
AD2E.thac0Table = THAC0_TABLE;
export function thac0At(group, level) {
  const table = AD2E.thac0Table[group];
  if (level >= 1 && level <= table.length) return table[level - 1];
  const { divisor, step } = AD2E.thac0Progression[group];
  return 20 - Math.floor((Math.max(level, 1) - 1) / divisor) * step;
}

/**
 * Proficiencies: PHB Table 34 slots per group and Table 38 nonweapon groups per class (generated by
 * tools/build-proficiency-data.py). A new slot comes at every level evenly divisible by the rate.
 */
AD2E.proficiencySlots = PROFICIENCY_SLOTS;
AD2E.proficiencyGroups = PROFICIENCY_GROUPS;
AD2E.proficiencyKinds = { weapon: "AD2E.Prof.Weapon", nonweapon: "AD2E.Prof.Nonweapon" };
AD2E.nonweaponGroups = { general: "AD2E.Prof.Group.general", priest: "AD2E.Group.priest", rogue: "AD2E.Group.rogue",
  warrior: "AD2E.Group.warrior", wizard: "AD2E.Group.wizard" };
/** Default nonweapon groups per class group when no class item is present (Table 38 base classes). */
AD2E.defaultProficiencyGroups = { warrior: ["warrior", "general"], wizard: ["wizard", "general"],
  priest: ["priest", "general"], rogue: ["rogue", "general"] };

/**
 * Attacks per round as [attacks, rounds]: PHB Table 15 (warrior melee) and Table 35 (specialists, by
 * fighter level; columns melee, lightCrossbow, heavyCrossbow, thrownDagger, thrownDart, otherMissile).
 * Generated by tools/build-level-tables.py.
 */
AD2E.warriorAttacks = WARRIOR_ATTACKS;
AD2E.specialistAttacks = SPECIALIST_ATTACKS;
/** Weapon specialization (Weapon Specialization (PHB)): extra slots, and the melee hit/damage and point-blank bonuses. */
AD2E.specialization = { classes: ["fighter"], extraSlots: { bow: 2, crossbow: 1, other: 1 }, meleeHit: 1, meleeDamage: 2,
  pointBlank: 2, pointBlankFeet: { bow: "6-30", crossbow: "6-60" } };
/** Missile range modifiers to the attack roll (Missile Weapons in Combat (PHB)): medium -2, long -5. */
AD2E.rangeModifiers = { pointBlank: 2, short: 0, medium: -2, long: -5 };

/** Rate in a [{min, max, rate: [attacks, rounds]}] table for a level. */
export function attackRate(table, level) {
  return table.find(r => level >= r.min && level <= r.max)?.rate ?? [1, 1];
}

/** "3/2" for [3, 2]; "1" for [1, 1]. */
export function formatRate([attacks, rounds]) {
  return rounds === 1 ? `${attacks}` : `${attacks}/${rounds}`;
}

/** Armour item kinds (Armor List (PHB)). */
AD2E.armorKinds = { body: "AD2E.Armor.body", shield: "AD2E.Armor.shield", helmet: "AD2E.Armor.helmet" };

/** "AC 5" / "Shield +1 (+2 vs. missiles), 1 attack/round" / "Helmet" for an armour item (localized). */
export function armorSummary(sys) {
  const i18n = k => game.i18n.localize(k);
  const magic = sys.bonus ? ` (${sys.bonus > 0 ? "+" : ""}${sys.bonus})` : "";
  if (sys.kind === "body") return `${i18n("AD2E.Armor.AC")} ${sys.ac ?? "—"}${magic}`;
  if (sys.kind === "shield") {
    const s = sys.shield;
    return `${i18n("AD2E.Armor.shield")} +${s.melee + sys.bonus}`
      + (s.missile !== s.melee ? ` (+${s.missile + sys.bonus} ${i18n("AD2E.Armor.VsMissiles")})` : "")
      + `, ${s.attacks ? game.i18n.format("AD2E.Armor.AttacksPerRound", { n: s.attacks }) : i18n("AD2E.Armor.AnyFrontal")}`;
  }
  return i18n("AD2E.Armor.helmet") + (magic ? ` ${magic}` : "");
}

/**
 * Encumbrance and movement (generated by tools/build-movement-tables.py): Table 47 categories, Table 48 modified
 * movement rates, Table 64 base movement per race. Strength key = score * 100 + exceptional (18/00 = 1900).
 */
AD2E.encumbranceTable = ENCUMBRANCE_TABLE;
AD2E.movementTable = MOVEMENT_TABLE;
AD2E.baseMovement = BASE_MOVEMENT;
AD2E.encumbranceCategories = ["unencumbered", "light", "moderate", "heavy", "severe"];
/** Encumbrance rules (world setting): off, basic categories (Table 47) or specific movement (Table 48). */
AD2E.encumbranceRules = { none: "AD2E.Enc.RuleNone", basic: "AD2E.Enc.RuleBasic", specific: "AD2E.Enc.RuleSpecific" };
/** Clothing worn is added to the load: "Add five pounds for clothing, if any is worn." (Encumbrance (PHB)). */
AD2E.clothingWeight = 5;
/** Coins, highest first: value in copper pieces (PHB Table 42); 50 coins of any metal weigh a pound (DMG). */
AD2E.coins = ["pp", "gp", "ep", "sp", "cp"];
AD2E.coinValues = COIN_VALUES;
AD2E.coinsPerPound = COINS_PER_POUND;
/** Equipment item categories (PHB Table 44 lists). */
AD2E.equipmentCategories = { gear: "AD2E.Gear.gear", clothing: "AD2E.Gear.clothing", provisions: "AD2E.Gear.provisions",
  lodging: "AD2E.Gear.lodging", tack: "AD2E.Gear.tack", animal: "AD2E.Gear.animal", transport: "AD2E.Gear.transport",
  service: "AD2E.Gear.service", component: "AD2E.Gear.component" };

/** "2 gp · 2 lb each · holds 50 lb (3'×2'×1')" / animal "carries 180 / 270 / 360 lb" for an equipment item. */
export function equipmentSummary(sys) {
  const i18n = k => game.i18n.localize(k);
  const parts = [sys.cost];
  if (sys.weight !== null) parts.push(`${sys.weight} lb${sys.quantity > 1 ? ` ${i18n("AD2E.Gear.Each")}` : ""}`);
  if (sys.capacity.weight !== null) {
    parts.push(game.i18n.format("AD2E.Gear.Holds", { lb: sys.capacity.weight })
      + (sys.capacity.volume ? ` (${sys.capacity.volume})` : ""));
  }
  // Spell components (POSM Table 16): scarcity, acquisition, perishable, in a wizard's laboratory.
  const c = sys.component;
  if (sys.category === "component" && c) {
    parts.push([c.scarcity, c.acquisition, c.perishable ? i18n("AD2E.Gear.Perishable") : "", c.laboratory ? i18n("AD2E.Gear.Laboratory") : ""]
      .filter(Boolean).join(", "));
  }
  if (sys.load.full !== null) {
    parts.push(game.i18n.format("AD2E.Gear.Carries", { full: sys.load.full, half: sys.load.half, quarter: sys.load.quarter }));
  }
  return parts.filter(Boolean).join(" · ");
}

AD2E.coinDenominations = { pp: "AD2E.Coin.pp", gp: "AD2E.Coin.gp", ep: "AD2E.Coin.ep", sp: "AD2E.Coin.sp",
  cp: "AD2E.Coin.cp", other: "AD2E.Coin.other" };

/** Strength key for Tables 47/48: score * 100, plus the exceptional percentile at 18 (18/00 = 1900). */
export function strengthKey(score, exceptional = 0) {
  return score * 100 + (score === 18 && exceptional > 0 ? exceptional : 0);
}

/** Monster actor roles (the monster sheet also serves hirelings, mounts and pets). */
AD2E.monsterRoles = { monster: "AD2E.Monster.Role.monster", hireling: "AD2E.Monster.Role.hireling",
  mount: "AD2E.Monster.Role.mount", pack: "AD2E.Monster.Role.pack", pet: "AD2E.Monster.Role.pet",
  familiar: "AD2E.Monster.Role.familiar" };
/** DMG Table 39 (generated): index 0 = less than one Hit Die, index n = n Hit Dice, last = 16 and more. */
AD2E.creatureThac0 = CREATURE_THAC0;

/**
 * Parse a Monstrous Manual Hit Dice entry: "3", "3+3", "1-1", "1/2", "2-8 hp", "1d8+76 hp", "2-4 hit points"; also
 * "14 (base)" and "12 (8)" (leading value), "6+6 or 9+9" (first alternative) and "3-8" / "5-10 HD" (a range of
 * Hit Dice: the lower end; "n-m" with m <= n is n dice minus m points, as in "1-1").
 * - hit points: n d8 + m (Hit Dice are d8), "1/2" = 1d4, hit-point entries as written ("x-y hp" = a roll covering x-y);
 * - thac0Index: Hit Dice for Table 39, "When a creature has three or more points added to its Hit Dice, count
 *   another die"; less than one Hit Die (1-1, 1/2, hit points only) = 0;
 * - saveLevel: "Any additions to their Hit Dice are counted as well, at the rate of one die for every four points or
 *   fraction thereof" (The Saving Throw (DMG)); less than one Hit Die = 0.
 */
export function creatureHitDice(text) {
  // first alternative: "6+6 or 9+9", "8, 12, or 16", "3, but see below", "2 to 5", "1+1 to 4+4"
  const t = String(text ?? "").trim().replace(/½/g, "1/2").replace(/¼/g, "1/4").split(/\s+or\s+|,|\s+to\s+/i)[0].trim();
  const hpOnly = formula => ({ dice: 0, bonus: 0, formula, thac0Index: 0, saveLevel: 0, hpOnly: true });
  const range = (lo, hi) => (lo === hi ? `${lo}` : lo === 1 ? `1d${hi}` : hi % lo === 0 ? `${lo}d${hi / lo}` : `1d${hi - lo + 1}+${lo - 1}`);
  // "16 + 2-7 hit points" (giants): Hit Dice plus a range of extra hit points
  let g = t.match(/^(\d+)\s*\+\s*(\d+)\s*-\s*(\d+)\s*(?:hp|hit points)$/i);
  if (g) {
    const dice = Number(g[1]);
    const lo = Number(g[2]);
    return { dice, bonus: lo, formula: `${dice}d8+${range(lo, Number(g[3]))}`, thac0Index: dice + (lo >= 3 ? 1 : 0),
      saveLevel: dice + Math.ceil(lo / 4), hpOnly: false };
  }
  let m = t.match(/^(\d+d\d+(?:\s*[+-]\s*\d+)?)\s*(?:hp|hit points)$/i);
  if (m) return hpOnly(m[1].replace(/\s/g, ""));
  m = t.replace(/\(.*?\)/g, "").trim().match(/^(\d+)\s*(?:-\s*(\d+))?\s*(?:hp|hit points?)$/i);
  if (m) return hpOnly(range(Number(m[1]), Number(m[2] ?? m[1])));
  const core = t.replace(/\(.*?\)/g, "").replace(/\s*HD$/i, "").replace(/\+$/, "").trim();
  // fractions of a Hit Die: "1/2" = 1d4, "1/4" = 1d2, optionally "+n"
  const frac = core.match(/^1\/(2|4)\s*(?:\+\s*(\d+))?$/);
  if (frac) {
    const plus = Number(frac[2] ?? 0);
    return { dice: 1 / Number(frac[1]), bonus: plus, formula: `1d${8 / Number(frac[1])}${plus ? `+${plus}` : ""}`,
      thac0Index: 0, saveLevel: 0, hpOnly: false };
  }
  m = core.match(/^(\d+)\s*([+-])\s*(\d+)$/) ?? core.match(/^(\d+)$/);
  if (!m) return { dice: 1, bonus: 0, formula: "1d8", thac0Index: 1, saveLevel: 1, hpOnly: false, invalid: true };
  let dice = Number(m[1]);
  let bonus = m[2] ? (m[2] === "+" ? 1 : -1) * Number(m[3]) : 0;
  if (bonus < 0 && -bonus > dice) bonus = 0; // "3-8": a range of Hit Dice, use the lower end
  const formula = bonus ? `${dice}d8${bonus > 0 ? "+" : ""}${bonus}` : `${dice}d8`;
  if (bonus < 0) return { dice, bonus, formula, thac0Index: dice - 1, saveLevel: Math.max(dice - 1, 0), hpOnly: false };
  return { dice, bonus, formula, thac0Index: dice + (bonus >= 3 ? 1 : 0), saveLevel: dice + Math.ceil(bonus / 4), hpOnly: false };
}

/**
 * Spells. SPELL_PROGRESSION (generated): per caster table and class level, { casting level, slots per spell level }.
 * Class identifier -> table; wizard and bard tables cast wizard spells, the others priest spells.
 */
AD2E.spellProgression = SPELL_PROGRESSION;
AD2E.spellKinds = { wizard: "AD2E.Spell.wizard", priest: "AD2E.Spell.priest" };
AD2E.casterTables = { mage: "wizard", abjurer: "wizard", conjurer: "wizard", diviner: "wizard", enchanter: "wizard",
  illusionist: "wizard", invoker: "wizard", necromancer: "wizard", transmuter: "wizard",
  cleric: "priest", druid: "priest", paladin: "paladin", ranger: "ranger", bard: "bard" };
AD2E.casterKinds = { wizard: "wizard", bard: "wizard", priest: "priest", paladin: "priest", ranger: "priest" };
/** Spheres open to paladins and rangers (Paladin (PHB), Ranger (PHB)); sphere "All" is open to every priest. */
AD2E.limitedSpheres = { paladin: ["combat", "divination", "healing", "protection"], ranger: ["plant", "animal"] };
/** Priest spell levels that need Wisdom (Table 24 footnotes): 6th 17+, 7th 18+. */
AD2E.priestWisdomLevels = { 6: 17, 7: 18 };

/** Four-letter stems of school names: "Invoc./Evoc." and "Invocation/Evocation" -> ["invo", "evoc"]. */
export function schoolStems(text) {
  return String(text ?? "").toLowerCase().split(/[\s,/;]+/).map(w => w.replace(/[^a-z]/g, "").slice(0, 4)).filter(w => w.length >= 4);
}

/**
 * Class abilities (generated tables: CLASS_TABLES from tools/build-class-ability-tables.py).
 * Thief skills (PHB Tables 26-29): base + race + Dexterity + armour + discretionary points, "no skill can be raised
 * above 95 percent, including all adjustments" (Thief (PHB)); 60 points at 1st level, 30 per level after.
 * Bard abilities (Table 33): race and Dexterity adjustments as for thieves; 20 points at 1st level, 15 per level after
 * (Bard (PHB)). Ranger hide in shadows / move silently (Table 18): race and Dexterity adjustments only, studded leather
 * or lighter armour, halved outside natural surroundings (Ranger (PHB)).
 */
AD2E.classTables = CLASS_TABLES;
AD2E.thiefSkills = ["pp", "ol", "rt", "ms", "hs", "dn", "cw", "rl"];
AD2E.skillClasses = {
  thief: { skills: AD2E.thiefSkills, base: "thief", points: [60, 30], cap: 95, armor: true },
  bard: { skills: ["cw", "dn", "pp", "rl"], base: "bard", points: [20, 15], cap: null, armor: true },
  ranger: { skills: ["hs", "ms"], base: "ranger", points: null, cap: null, armor: false }
};
/** Thief discretionary points per skill: at most 30 at 1st level, 15 more per level after (Thief (PHB)). */
AD2E.thiefPointLimits = { first: 30, perLevel: 15 };
/** Backstab: +4 to hit for the rear attack (Thief Skill Explanations (PHB)). */
AD2E.backstabHit = 4;
/** Find/remove traps: a roll of 96-100 sets the trap off (Thief Skill Explanations (PHB)). */
AD2E.trapSpringRoll = 96;
/** Paladin saving throw bonus: "+2 bonus to all saving throws" (Paladin (PHB)). */
AD2E.paladinSaveBonus = 2;
/** Body armour names -> Table 29 column ("leather": no column, no adjustment; anything else heavier: not usable). */
export function thiefArmorColumn(name) {
  const n = String(name ?? "").toLowerCase();
  if (!n) return "none";
  if (n.includes("elven chain")) return "elvenChain";
  if (/padded|hide|studded/.test(n)) return "padded";
  if (/chain|ring/.test(n)) return "chain";
  if (n.includes("leather")) return "leather";
  return "heavy";
}
/** Turning undead: clerics at their level; paladins from 3rd level as a cleric two levels lower (Turning Undead (PHB)). */
AD2E.turnUndead = { cleric: { from: 1, offset: 0 }, paladin: { from: 3, offset: -2 } };

/**
 * PHB class features shown on the Class Abilities tab: [key, level gained]. Names and short summaries are in
 * lang (AD2E.Feature.<class>.<key>); the class page (Class item URL) has the full rules.
 */
AD2E.classFeatures = {
  fighter: [["specialization", 1], ["followers", 9]],
  paladin: [["detectEvil", 1], ["saves", 1], ["disease", 1], ["layOnHands", 1], ["cureDisease", 1], ["aura", 1],
    ["turnUndead", 3], ["spells", 9], ["noFollowers", 9]],
  ranger: [["twoWeapons", 1], ["tracking", 1], ["stealth", 1], ["speciesEnemy", 1], ["animals", 1], ["spells", 8], ["followers", 10]],
  cleric: [["turnUndead", 1], ["followers", 8], ["stronghold", 9]],
  druid: [["noTurning", 1], ["language", 1], ["identify", 3], ["passPlants", 3], ["woodlandLanguages", 3], ["charmImmunity", 7], ["shapechange", 7]],
  thief: [["skills", 1], ["backstab", 1], ["followers", 10], ["scrolls", 10]],
  bard: [["abilities", 1], ["influence", 1], ["counterSong", 1], ["spells", 2], ["scrolls", 10]]
};
/**
 * Wizards (Wizard (PHB), Specialist Wizard (PHB)): entries [key, level, namespace]; the namespace selects the lang
 * group (AD2E.Feature.wizard / .specialist) shared by the mage and the eight specialists.
 */
const WIZARD_FEATURES = [["spellBook", 1, "wizard"], ["learnSpells", 1, "wizard"], ["noArmor", 1, "wizard"],
  ["magicItems", 1, "wizard"], ["scrollsPotions", 9, "wizard"], ["noStronghold", 1, "wizard"]];
const SPECIALIST_FEATURES = [["extraSpell", 1, "specialist"], ["schoolSaves", 1, "specialist"], ["learnBonus", 1, "specialist"],
  ["opposition", 1, "specialist"], ["newSpellLevel", 1, "specialist"]];
AD2E.classFeatures.mage = WIZARD_FEATURES;
for (const id of ["abjurer", "conjurer", "diviner", "enchanter", "illusionist", "invoker", "necromancer", "transmuter"]) {
  AD2E.classFeatures[id] = [...WIZARD_FEATURES, ...SPECIALIST_FEATURES];
}

AD2E.thac0Progression = {
  warrior: { divisor: 1, step: 1 },
  priest:  { divisor: 3, step: 2 },
  rogue:   { divisor: 2, step: 1 },
  wizard:  { divisor: 3, step: 1 }
};

/** Hit die size per group (used for CON bonus bookkeeping; HP itself is entered manually). */
AD2E.hitDie = { warrior: 10, priest: 8, rogue: 6, wizard: 4 };

/**
 * Kit modifiers (system.modifiers on kit items, curated from the kit pages by tools/build-kit-mechanics.py).
 * Effective value at a level: null below `from`; otherwise value + step x floor((level - from) / every).
 */
export function kitModifierValue(mod, level) {
  if (level < (mod.from ?? 1)) return null;
  return mod.value + (mod.every > 0 ? mod.step * Math.floor((level - (mod.from ?? 1)) / mod.every) : 0);
}
/** Whether equipped body armour (an item or null) meets a modifier's armour requirement. */
export function kitArmorMatches(armor, body) {
  if (!armor) return true;
  const name = String(body?.name ?? "").toLowerCase();
  if (armor === "none") return !body;
  if (armor === "light") return !body || (/\b(leather|padded)\b/.test(name) && !name.includes("studded"));
  if (armor === "any") return !!body;
  return false;
}
/** Whether a modifier key ("" = all, or a comma-separated list) covers `key`. */
export function kitKeyMatches(modKey, key) {
  if (!modKey) return true;
  return modKey.split(",").map(k => k.trim()).includes(key);
}
AD2E.kitTargets = ["attack", "damage", "save", "ac", "skill", "proficiency", "ability", "initiative", "surprise", "reaction", "hp", "score"];

/**
 * Magical items and treasure (generated: TREASURE_TABLES from tools/build-treasure-tables.py).
 * Magical item categories follow DMG Table 88 (Tables 89-104); magical armour and weapons are armour and weapon items
 * with a magical bonus. Consumed on use (one from the quantity): potions and oils, scrolls, dusts and stones.
 * Gems: DMG Table 85 base value per class (uncut stones 10%); objects of art (jewellery and the like): Table 87.
 */
AD2E.treasureTables = TREASURE_TABLES;
AD2E.magicCategories = Object.fromEntries(TREASURE_TABLES.magicCategories.map(c => [c.key, `AD2E.Magic.Category.${c.key}`]));
AD2E.magicConsumable = ["potion", "scroll", "dust"];
AD2E.treasureKinds = { gem: "AD2E.Treasure.Kind.gem", jewellery: "AD2E.Treasure.Kind.jewellery", art: "AD2E.Treasure.Kind.art" };
AD2E.gemClasses = Object.fromEntries(TREASURE_TABLES.gemClasses.map(g => [g.key, `AD2E.Treasure.Gem.${g.key}`]));
/** DMG Table 85 base value (gp) of a gem class; null for an unknown class. */
export function gemBaseValue(key) {
  return TREASURE_TABLES.gemClasses.find(g => g.key === key)?.value ?? null;
}

/** Surprise (generated: ENCOUNTER_TABLES): 1d10, surprised on 1-3; DMG Table 57 situational modifiers. */
AD2E.encounterTables = ENCOUNTER_TABLES;
