/**
 * The sha'ir's gen as an actor (Requesting a Spell (AA), section Gens; Summoning a Familiar (AA); rules in
 * module/rules/shair-tables.mjs, generated by tools/build-shair-tables.py).
 *  - A monster actor (role "familiar", identifier "gen-<kind>") linked by character `system.gen.uuid`: AC 5, MV 9 (air
 *    also Fl 12 (B), water Sw 12), Low intelligence, size S, one attack of 1d6 (earth 2d6); hit points half the
 *    master's current maximum, Hit Dice half the master's level (rounded down; below 1: "1/2"), so the THAC0 of a
 *    monster of those Hit Dice; saving throws at twice the master's level (wizard table: the master's class).
 *    The active GM keeps these in step with the master (level, maximum hit points).
 *  - Loyalty (its morale value): 18 for the first gen, -1 per replacement (dismissed or lost), at least 5; +1 when
 *    the master's alignment is the gen's tendency (air lawful good, fire lawful evil, water chaotic good, earth chaotic
 *    evil; the owner adjusts it).
 *  - Protection against its element (province: air wind, fire flame, water sea, earth sand): attacks -2 to hit (a tick
 *    box in attack dialogs), saving throws +2 (a tick box in the save dialog), damage -2 per die, at least 1 per die
 *    (applied from damage messages carrying the element's dice). The gen always; the sha'ir while the gen is within
 *    10 feet (`system.gen.near`).
 *  - Death: the sha'ir's hit points drop by half; at 0 or fewer, a saving throw vs. death magic: success leaves 1 hit
 *    point, failure is death (a button on the sha'ir's sheet, as for familiars).
 *  - Brought back to life: "a permanent 1-point penalty in morale and loyalty" (`raiseGen`).
 *  - Link broken by dispel magic or the master's death (the gen returns to its plane; the active GM marks it when the
 *    master dies): summoning that same gen restores the link, no replacement (`breakGenLink`, `summonGen`).
 *  - Away (`sendGenAway`): forced beyond 100 yards or threatened more than 10 feet away: back in 1d6 turns; following
 *    its master to another plane: 1d6 days (1d6 rounds to an elemental plane); an errand: until recalled. While away
 *    or unlinked it gives no protection; the sheet notes that the sha'ir senses it is alive. The active GM returns it
 *    when world time passes `awayUntil`.
 *  - Charmed: it turns against its master only if a morale check fails (noted on the gen).
 * The Monstrous Compendium entry (MC13) gives the fire gen MV 18; Arabian Adventures (used here) "move normally".
 */
import { SHAIR } from "./rules/shair-tables.mjs";
import { GEN_KINDS } from "./shair.mjs";

export { GEN_KINDS };
const resolve = uuid => (uuid ? (foundry.utils.fromUuidSync ?? globalThis.fromUuidSync)?.(uuid, { strict: false }) ?? null : null);
const esc = v => foundry.utils.escapeHTML?.(String(v ?? "")) ?? String(v ?? "");

/** Elemental province of a gen kind (air: wind, fire: flame, water: sea, earth: sand). */
export function genProvince(kind) {
  return SHAIR.genKinds[kind]?.province ?? null;
}

/** Hit Dice text for half the master's level ("1/2" below one Hit Die). */
export function genHitDice(level) {
  const half = Math.floor((level ?? 1) / 2);
  return half >= 1 ? String(half) : "1/2";
}

/** Loyalty (morale value) of a gen: 18 - replacements, at least 5, +1 for a master of the gen's tendency. */
export function genLoyalty(replacements = 0, alignment = "", kind = "") {
  const L = SHAIR.genLoyalty;
  const base = Math.max(L.first + L.perReplacement * Math.max(replacements, 0), L.min);
  return base + (alignment && SHAIR.genTendencies[kind] === alignment ? SHAIR.genAlignment : 0);
}

/** Monster data for a gen of `kind` serving `master` (a character). */
export function genActorData(master, kind, replacements = 0) {
  const S = SHAIR.genStats;
  const k = SHAIR.genKinds[kind] ?? {};
  const level = master.system.level ?? 1;
  const hp = Math.max(Math.floor((master.system.hp?.max ?? 1) * SHAIR.genDeath.factor), 1);
  const loyalty = genLoyalty(replacements, master.system.alignment, kind);
  return {
    name: game.i18n.format("AD2E.Gen.ActorName", { kind: game.i18n.localize(`AD2E.Shair.Kind.${kind}`), name: master.name }),
    type: "monster",
    img: "icons/svg/fire.svg",
    ownership: foundry.utils.deepClone(master.ownership ?? {}),
    system: {
      identifier: `gen-${kind}`, role: "familiar", intelligence: S.intelligence, alignment: "N", size: S.size,
      ac: { base: S.ac }, movement: { base: S.move, text: [String(S.move), k.move].filter(Boolean).join(", ") },
      hitDice: genHitDice(level), hp: { value: hp, max: hp }, saveGroup: "wizard", saveLevel: level * SHAIR.genSaves,
      attacks: [{ name: game.i18n.localize("AD2E.Gen.Attack"), damage: k.damage ?? S.damage, bonus: 0 }],
      morale: { value: loyalty, text: String(loyalty) }, numberAppearing: "1",
      specialAttacks: kind === "fire" ? game.i18n.localize("AD2E.Gen.ProduceFlame") : "",
      specialDefenses: `${game.i18n.format("AD2E.Gen.WardText", { province: game.i18n.localize(`AD2E.Elemental.Province.${genProvince(kind)}`) })}. ${game.i18n.localize("AD2E.Gen.CharmText")}`,
      url: "https://adnd2e.fandom.com/wiki/Requesting_a_Spell_(AA)"
    }
  };
}

/** Whether an actor is a gen (monster with identifier gen-<kind>); its kind or null. */
export function genKindOf(actor) {
  const m = actor?.type === "monster" ? String(actor.system?.identifier ?? "").match(/^gen-(air|fire|water|earth)$/) : null;
  return m ? m[1] : null;
}

function genDead(actor) {
  return !actor?.system || (actor.system.hp?.value ?? 1) <= 0 || !!actor.system.hp?.dead;
}

/** A character's gen: { actor, uuid, missing, dead, kind, near, deathResolved }. */
export function genInfo(character) {
  const g = character?.system?.gen ?? {};
  const actor = resolve(g.uuid);
  const usable = !!actor?.system;
  return { uuid: g.uuid ?? "", actor: usable ? actor : null, missing: !!g.uuid && !usable, dead: usable && genDead(actor),
    kind: genKindOf(actor) ?? g.kind ?? "", near: g.near !== false, deathResolved: !!g.deathResolved, broken: !!g.broken,
    away: !!g.awayReason, awayReason: g.awayReason ?? "", awayUntil: g.awayUntil ?? null };
}

/** The province an actor is protected against by a gen (the gen itself; a sha'ir with a living gen within 10 ft), or null. */
export function genWardProvince(actor) {
  const own = genKindOf(actor);
  if (own) return genDead(actor) ? null : genProvince(own);
  if (actor?.type !== "character" || !actor.system?.gen?.uuid) return null;
  const info = genInfo(actor);
  return info.actor && !info.dead && info.near && !info.broken && !info.away ? genProvince(info.kind) : null;
}

/** Damage a gen-protected actor takes from a damage message's element flag (-2 per die, at least 1 per die), or null. */
export function genWardedDamage(actor, flag) {
  const province = genWardProvince(actor);
  if (!province || !flag?.provinces?.includes(province) || !Array.isArray(flag.dice)) return null;
  const W = SHAIR.genWard;
  return Math.max(flag.dice.reduce((n, v) => n + Math.max(v + W.perDie, W.minPerDie), 0) + (flag.flat ?? 0), 0);
}

/**
 * Summon a gen (1d20 hours of fasting and communing, Summoning a Familiar (AA)): creates the gen actor, owned like the
 * sha'ir, and links it. A sha'ir who had a gen before counts a replacement (lower loyalty, longer searches).
 */
export async function summonGen(character) {
  const i18n = k => game.i18n.localize(k);
  const kind = character.system.gen?.kind;
  if (!GEN_KINDS.includes(kind)) return ui.notifications.warn(i18n("AD2E.Shair.NoGen"));
  const current = genInfo(character);
  // A broken link (dispel magic, the master raised from death): summoning the same gen reforges it.
  if (current.actor && !current.dead && current.broken) return relinkGen(character, current);
  if (current.actor && !current.dead) return ui.notifications.warn(game.i18n.format("AD2E.Gen.HasOne", { name: current.actor.name }));
  const ok = await foundry.applications.api.DialogV2.confirm({ window: { title: i18n("AD2E.Gen.SummonTitle") },
    content: `<p>${esc(game.i18n.format("AD2E.Gen.SummonText", { name: character.name, time: SHAIR.genSummon }))}</p>`, rejectClose: false });
  if (!ok) return null;
  const replacements = (character.system.gen.replacements ?? 0) + (current.uuid ? 1 : 0);
  const time = await new Roll(SHAIR.genSummon).evaluate();
  const actor = await Actor.implementation.create(genActorData(character, kind, replacements));
  if (!actor) return null;
  await character.update({ "system.gen.uuid": actor.uuid, "system.gen.near": true, "system.gen.deathResolved": false,
    "system.gen.replacements": replacements });
  await time.toMessage({ speaker: ChatMessage.getSpeaker({ actor: character }), flavor: esc(game.i18n.format("AD2E.Gen.Summoned",
    { name: character.name, gen: actor.name, hours: time.total, loyalty: actor.system.morale.value })) });
  return actor;
}

/** Reforge a broken link with the same gen: 1d20 hours of summoning and binding, no replacement. */
async function relinkGen(character, current) {
  const ok = await foundry.applications.api.DialogV2.confirm({ window: { title: game.i18n.localize("AD2E.Gen.RelinkTitle") },
    content: `<p>${esc(game.i18n.format("AD2E.Gen.RelinkText", { name: character.name, gen: current.actor.name, time: SHAIR.genSummon }))}</p>`, rejectClose: false });
  if (!ok) return null;
  const time = await new Roll(SHAIR.genSummon).evaluate();
  await character.update({ "system.gen.broken": false, "system.gen.awayReason": "", "system.gen.awayUntil": null, "system.gen.near": true });
  await time.toMessage({ speaker: ChatMessage.getSpeaker({ actor: character }), flavor: esc(game.i18n.format("AD2E.Gen.Relinked",
    { name: character.name, gen: current.actor.name, hours: time.total })) });
  return current.actor;
}

/** Break the link (dispel magic, or the master's death): no protection, no spells; the same gen can be summoned again. */
export async function breakGenLink(character, reason = "dispel") {
  const info = genInfo(character);
  if (!info.actor || info.broken) return;
  await character.update({ "system.gen.broken": true, "system.gen.awayReason": "", "system.gen.awayUntil": null });
  return ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: character }),
    content: `<p>${esc(game.i18n.format(`AD2E.Gen.Broken.${reason}`, { name: character.name, gen: info.actor.name }))}</p>` });
}

/** A dead gen brought back to life: full hit points, loyalty (morale) 1 lower for good. */
export async function raiseGen(character) {
  const info = genInfo(character);
  if (!info.actor || !info.dead) return;
  const g = info.actor.system;
  const loyalty = Math.max((g.morale?.value ?? 10) + SHAIR.genRaised, 2);
  await info.actor.update({ "system.hp.value": g.hp.max, "system.hp.dead": false, "system.morale.value": loyalty, "system.morale.text": String(loyalty) });
  await character.update({ "system.gen.raised": (character.system.gen.raised ?? 0) + 1, "system.gen.deathResolved": false });
  return ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: character }),
    content: `<p>${esc(game.i18n.format("AD2E.Gen.Raised", { gen: info.actor.name, loyalty }))}</p>` });
}

/**
 * The gen goes away (GM or owner): `reason` forced | threatened | plane | elemental (rolled time) | errand (until
 * recalled). Returns the seconds away (null: until recalled).
 */
export async function sendGenAway(character, reason) {
  const info = genInfo(character);
  const rule = SHAIR.genAway[reason];
  if (!info.actor || info.dead || info.broken || rule === undefined || reason === "yards") return null;
  let seconds = null;
  let text = game.i18n.format("AD2E.Gen.AwayErrand", { gen: info.actor.name });
  if (rule) {
    const roll = await new Roll(rule[0]).evaluate();
    seconds = roll.total * SHAIR.unitSeconds[rule[1]];
    text = game.i18n.format("AD2E.Gen.AwayFor", { gen: info.actor.name, n: roll.total, unit: game.i18n.localize(`AD2E.Shair.Unit.${rule[1]}`),
      reason: game.i18n.localize(`AD2E.Gen.Away.${reason}`) });
  }
  await character.update({ "system.gen.awayReason": reason, "system.gen.awayUntil": seconds === null ? null : game.time.worldTime + seconds });
  await ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: character }), content: `<p>${esc(text)}</p>` });
  return seconds;
}

/** The gen is back with its master. */
export async function genBack(character) {
  const info = genInfo(character);
  if (!info.away) return;
  await character.update({ "system.gen.awayReason": "", "system.gen.awayUntil": null });
  return ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: character }),
    content: `<p>${esc(game.i18n.format("AD2E.Gen.Back", { gen: info.actor?.name ?? "—", name: character.name }))}</p>` });
}

/** Status text for the sheet: away (with the sha'ir's sense that it lives) or link broken; "" otherwise. */
export function genStatusText(character, now = game.time?.worldTime ?? 0) {
  const info = genInfo(character);
  if (!info.actor) return "";
  if (info.broken) return game.i18n.localize("AD2E.Gen.LinkBroken");
  if (!info.away) return "";
  const left = info.awayUntil === null ? null : Math.max(Math.ceil((info.awayUntil - now) / 60), 0);
  return game.i18n.format(left === null ? "AD2E.Gen.AwayUntilRecalled" : "AD2E.Gen.AwayLeft", {
    reason: game.i18n.localize(`AD2E.Gen.Away.${info.awayReason}`), min: left }) + (info.dead ? "" : ` ${game.i18n.localize("AD2E.Gen.Sense")}`);
}

/** Dismiss the gen (no loss of hit points; the next gen's loyalty is lower). The actor stays for the GM to remove. */
export async function dismissGen(character) {
  const info = genInfo(character);
  if (!info.uuid) return;
  const ok = await foundry.applications.api.DialogV2.confirm({ window: { title: game.i18n.localize("AD2E.Gen.DismissTitle") },
    content: `<p>${esc(game.i18n.format("AD2E.Gen.DismissText", { gen: info.actor?.name ?? "—" }))}</p>`, rejectClose: false });
  if (!ok) return;
  return character.update({ "system.gen.uuid": "", "system.gen.deathResolved": false,
    "system.gen.replacements": (character.system.gen.replacements ?? 0) + 1 });
}

/**
 * The gen died: the sha'ir's hit points drop by half; at 0 or fewer, a saving throw vs. death magic (success: 1 hit
 * point; failure: death). Marks the death as resolved.
 */
export async function genDeath(character) {
  const i18n = k => game.i18n.localize(k);
  const hp = character.system.hp.value ?? 0;
  const halved = Math.floor(hp * SHAIR.genDeath.factor);
  let text = game.i18n.format("AD2E.Gen.DeathHalved", { name: character.name, from: hp, to: halved });
  let value = halved;
  let roll = null;
  if (halved <= 0) {
    const save = character.system.saves?.[SHAIR.genDeath.save];
    roll = await new Roll("1d20 + @bonus", { bonus: save?.bonus ?? 0 }).evaluate();
    const ok = roll.total >= (save?.value ?? 20);
    value = ok ? SHAIR.genDeath.survive : -10;
    text += ` ${game.i18n.format(ok ? "AD2E.Gen.DeathSaved" : "AD2E.Gen.DeathFailed", { needs: save?.value ?? "—" })}`;
  }
  await character.update({ "system.hp.value": value, "system.gen.deathResolved": true });
  const flavor = `${esc(i18n("AD2E.Gen.DeathTitle"))}: ${esc(text)}`;
  return roll ? roll.toMessage({ speaker: ChatMessage.getSpeaker({ actor: character }), flavor })
    : ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor: character }), content: `<p>${flavor}</p>` });
}

/** Keep a gen's Hit Dice, saving throw level and maximum hit points in step with its master (active GM). */
export async function syncGen(character) {
  const info = genInfo(character);
  if (!info.actor || info.dead) return;
  const level = character.system.level ?? 1;
  const max = Math.max(Math.floor((character.system.hp?.max ?? 1) * SHAIR.genDeath.factor), 1);
  const g = info.actor.system;
  const change = {};
  if (g.hitDice !== genHitDice(level)) change["system.hitDice"] = genHitDice(level);
  if (g.saveLevel !== level * SHAIR.genSaves) change["system.saveLevel"] = level * SHAIR.genSaves;
  if (g.hp.max !== max) {
    change["system.hp.max"] = max;
    change["system.hp.value"] = Math.max(Math.min(g.hp.value + (max - g.hp.max), max), 0);
  }
  if (Object.keys(change).length) await info.actor.update(change);
}

export function registerGenHooks() {
  // Gens away come back as world time passes (active GM).
  Hooks.on("updateWorldTime", async worldTime => {
    if (!game.users?.activeGM?.isSelf) return;
    for (const actor of game.actors ?? []) {
      const g = actor.type === "character" ? actor.system.gen : null;
      if (g?.awayReason && g.awayUntil !== null && g.awayUntil !== undefined && worldTime >= g.awayUntil) await genBack(actor);
    }
  });
  Hooks.on("updateActor", async (actor, changes) => {
    if (!game.users?.activeGM?.isSelf) return;
    // The master died: the gen is freed and returns to its plane (the link is broken; summoning it again after the
    // master is raised restores it).
    if (actor.type === "character" && actor.system.gen?.uuid && !actor.system.gen.broken && actor.system.hpState?.state === "dead"
      && (foundry.utils.hasProperty(changes, "system.hp.value") || foundry.utils.hasProperty(changes, "system.hp.dead"))) {
      await breakGenLink(actor, "masterDeath");
    }
    // The master changed: level or maximum hit points.
    if (actor.type === "character" && actor.system.gen?.uuid
      && (foundry.utils.hasProperty(changes, "system.level") || foundry.utils.hasProperty(changes, "system.hp.max")
        || foundry.utils.hasProperty(changes, "system.gen.uuid"))) await syncGen(actor);
    // A gen died: tell the GM to resolve it on the master's sheet.
    if (genKindOf(actor) && foundry.utils.hasProperty(changes, "system.hp.value") && genDead(actor)) {
      const master = game.actors.find(a => a.type === "character" && a.system.gen?.uuid === actor.uuid);
      if (master && !master.system.gen.deathResolved) {
        await ChatMessage.create({ speaker: ChatMessage.getSpeaker({ actor }), whisper: game.users.filter(u => u.isGM).map(u => u.id),
          content: `<p>${esc(game.i18n.format("AD2E.Gen.Died", { gen: actor.name, name: master.name }))}</p>` });
      }
    }
  });
}
