/**
 * GENERATED by tools/build-ability-tables.py - do not edit by hand.
 * Numeric data from the AD&D 2e fandom wiki ability tables (PHB Tables 1-6), as a
 * starter set for testing. Verify against an owned Player's Handbook.
 * Sources:
 *   str: https://adnd2e.fandom.com/wiki/Strength_(PHB) (revision 177331)
 *   dex: https://adnd2e.fandom.com/wiki/Dexterity_(PHB) (revision 177329)
 *   con: https://adnd2e.fandom.com/wiki/Constitution_(PHB) (revision 250527)
 *   int: https://adnd2e.fandom.com/wiki/Intelligence (revision 171781)
 *   wis: https://adnd2e.fandom.com/wiki/Wisdom_(PHB) (revision 177327)
 *   cha: https://adnd2e.fandom.com/wiki/Charisma_(PHB) (revision 177326)
 */
export const ABILITY_TABLES = {
  "str": [
    {
      "min": 1,
      "max": 1,
      "hit": -5,
      "dmg": -4,
      "weight": 1,
      "press": 3,
      "openDoors": 1,
      "openLocked": null,
      "bendBars": 0
    },
    {
      "min": 2,
      "max": 2,
      "hit": -3,
      "dmg": -2,
      "weight": 1,
      "press": 5,
      "openDoors": 1,
      "openLocked": null,
      "bendBars": 0
    },
    {
      "min": 3,
      "max": 3,
      "hit": -3,
      "dmg": -1,
      "weight": 5,
      "press": 10,
      "openDoors": 2,
      "openLocked": null,
      "bendBars": 0
    },
    {
      "min": 4,
      "max": 5,
      "hit": -2,
      "dmg": -1,
      "weight": 10,
      "press": 25,
      "openDoors": 3,
      "openLocked": null,
      "bendBars": 0
    },
    {
      "min": 6,
      "max": 7,
      "hit": -1,
      "dmg": 0,
      "weight": 20,
      "press": 55,
      "openDoors": 4,
      "openLocked": null,
      "bendBars": 0
    },
    {
      "min": 8,
      "max": 9,
      "hit": 0,
      "dmg": 0,
      "weight": 35,
      "press": 90,
      "openDoors": 5,
      "openLocked": null,
      "bendBars": 1
    },
    {
      "min": 10,
      "max": 11,
      "hit": 0,
      "dmg": 0,
      "weight": 40,
      "press": 115,
      "openDoors": 6,
      "openLocked": null,
      "bendBars": 2
    },
    {
      "min": 12,
      "max": 13,
      "hit": 0,
      "dmg": 0,
      "weight": 45,
      "press": 140,
      "openDoors": 7,
      "openLocked": null,
      "bendBars": 4
    },
    {
      "min": 14,
      "max": 15,
      "hit": 0,
      "dmg": 0,
      "weight": 55,
      "press": 170,
      "openDoors": 8,
      "openLocked": null,
      "bendBars": 7
    },
    {
      "min": 16,
      "max": 16,
      "hit": 0,
      "dmg": 1,
      "weight": 70,
      "press": 195,
      "openDoors": 9,
      "openLocked": null,
      "bendBars": 10
    },
    {
      "min": 17,
      "max": 17,
      "hit": 1,
      "dmg": 1,
      "weight": 85,
      "press": 220,
      "openDoors": 10,
      "openLocked": null,
      "bendBars": 13
    },
    {
      "min": 18,
      "max": 18,
      "hit": 1,
      "dmg": 2,
      "weight": 110,
      "press": 255,
      "openDoors": 11,
      "openLocked": null,
      "bendBars": 16
    },
    {
      "min": 19,
      "max": 19,
      "hit": 3,
      "dmg": 7,
      "weight": 485,
      "press": 640,
      "openDoors": 16,
      "openLocked": 8,
      "bendBars": 50
    },
    {
      "min": 20,
      "max": 20,
      "hit": 3,
      "dmg": 8,
      "weight": 535,
      "press": 700,
      "openDoors": 17,
      "openLocked": 10,
      "bendBars": 60
    },
    {
      "min": 21,
      "max": 21,
      "hit": 4,
      "dmg": 9,
      "weight": 635,
      "press": 810,
      "openDoors": 17,
      "openLocked": 12,
      "bendBars": 70
    },
    {
      "min": 22,
      "max": 22,
      "hit": 4,
      "dmg": 10,
      "weight": 785,
      "press": 970,
      "openDoors": 18,
      "openLocked": 14,
      "bendBars": 80
    },
    {
      "min": 23,
      "max": 23,
      "hit": 5,
      "dmg": 11,
      "weight": 935,
      "press": 1130,
      "openDoors": 18,
      "openLocked": 16,
      "bendBars": 90
    },
    {
      "min": 24,
      "max": 24,
      "hit": 6,
      "dmg": 12,
      "weight": 1235,
      "press": 1440,
      "openDoors": 19,
      "openLocked": 17,
      "bendBars": 95
    },
    {
      "min": 25,
      "max": 25,
      "hit": 7,
      "dmg": 14,
      "weight": 1535,
      "press": 1750,
      "openDoors": 19,
      "openLocked": 18,
      "bendBars": 99
    }
  ],
  "strExceptional": [
    {
      "min": 1,
      "max": 50,
      "hit": 1,
      "dmg": 3,
      "weight": 135,
      "press": 280,
      "openDoors": 12,
      "openLocked": null,
      "bendBars": 20
    },
    {
      "min": 51,
      "max": 75,
      "hit": 2,
      "dmg": 3,
      "weight": 160,
      "press": 305,
      "openDoors": 13,
      "openLocked": null,
      "bendBars": 25
    },
    {
      "min": 76,
      "max": 90,
      "hit": 2,
      "dmg": 4,
      "weight": 185,
      "press": 330,
      "openDoors": 14,
      "openLocked": null,
      "bendBars": 30
    },
    {
      "min": 91,
      "max": 99,
      "hit": 2,
      "dmg": 5,
      "weight": 235,
      "press": 380,
      "openDoors": 15,
      "openLocked": 3,
      "bendBars": 35
    },
    {
      "min": 100,
      "max": 100,
      "hit": 3,
      "dmg": 6,
      "weight": 335,
      "press": 480,
      "openDoors": 16,
      "openLocked": 6,
      "bendBars": 40
    }
  ],
  "dex": [
    {
      "min": 1,
      "max": 1,
      "reaction": -6,
      "missile": -6,
      "ac": 5
    },
    {
      "min": 2,
      "max": 2,
      "reaction": -4,
      "missile": -4,
      "ac": 5
    },
    {
      "min": 3,
      "max": 3,
      "reaction": -3,
      "missile": -3,
      "ac": 4
    },
    {
      "min": 4,
      "max": 4,
      "reaction": -2,
      "missile": -2,
      "ac": 3
    },
    {
      "min": 5,
      "max": 5,
      "reaction": -1,
      "missile": -1,
      "ac": 2
    },
    {
      "min": 6,
      "max": 6,
      "reaction": 0,
      "missile": 0,
      "ac": 1
    },
    {
      "min": 7,
      "max": 7,
      "reaction": 0,
      "missile": 0,
      "ac": 0
    },
    {
      "min": 8,
      "max": 8,
      "reaction": 0,
      "missile": 0,
      "ac": 0
    },
    {
      "min": 9,
      "max": 9,
      "reaction": 0,
      "missile": 0,
      "ac": 0
    },
    {
      "min": 10,
      "max": 14,
      "reaction": 0,
      "missile": 0,
      "ac": 0
    },
    {
      "min": 15,
      "max": 15,
      "reaction": 0,
      "missile": 0,
      "ac": -1
    },
    {
      "min": 16,
      "max": 16,
      "reaction": 1,
      "missile": 1,
      "ac": -2
    },
    {
      "min": 17,
      "max": 17,
      "reaction": 2,
      "missile": 2,
      "ac": -3
    },
    {
      "min": 18,
      "max": 18,
      "reaction": 2,
      "missile": 2,
      "ac": -4
    },
    {
      "min": 19,
      "max": 19,
      "reaction": 3,
      "missile": 3,
      "ac": -4
    },
    {
      "min": 20,
      "max": 20,
      "reaction": 3,
      "missile": 3,
      "ac": -4
    },
    {
      "min": 21,
      "max": 21,
      "reaction": 4,
      "missile": 4,
      "ac": -5
    },
    {
      "min": 22,
      "max": 22,
      "reaction": 4,
      "missile": 4,
      "ac": -5
    },
    {
      "min": 23,
      "max": 23,
      "reaction": 4,
      "missile": 4,
      "ac": -5
    },
    {
      "min": 24,
      "max": 24,
      "reaction": 5,
      "missile": 5,
      "ac": -6
    },
    {
      "min": 25,
      "max": 25,
      "reaction": 5,
      "missile": 5,
      "ac": -6
    }
  ],
  "con": [
    {
      "min": 1,
      "max": 1,
      "hp": -3,
      "warrior": -3,
      "systemShock": 25,
      "resurrection": 30,
      "poison": -2,
      "regen": null
    },
    {
      "min": 2,
      "max": 2,
      "hp": -2,
      "warrior": -2,
      "systemShock": 30,
      "resurrection": 35,
      "poison": -1,
      "regen": null
    },
    {
      "min": 3,
      "max": 3,
      "hp": -2,
      "warrior": -2,
      "systemShock": 35,
      "resurrection": 40,
      "poison": 0,
      "regen": null
    },
    {
      "min": 4,
      "max": 4,
      "hp": -1,
      "warrior": -1,
      "systemShock": 40,
      "resurrection": 45,
      "poison": 0,
      "regen": null
    },
    {
      "min": 5,
      "max": 5,
      "hp": -1,
      "warrior": -1,
      "systemShock": 45,
      "resurrection": 50,
      "poison": 0,
      "regen": null
    },
    {
      "min": 6,
      "max": 6,
      "hp": -1,
      "warrior": -1,
      "systemShock": 50,
      "resurrection": 55,
      "poison": 0,
      "regen": null
    },
    {
      "min": 7,
      "max": 7,
      "hp": 0,
      "warrior": 0,
      "systemShock": 55,
      "resurrection": 60,
      "poison": 0,
      "regen": null
    },
    {
      "min": 8,
      "max": 8,
      "hp": 0,
      "warrior": 0,
      "systemShock": 60,
      "resurrection": 65,
      "poison": 0,
      "regen": null
    },
    {
      "min": 9,
      "max": 9,
      "hp": 0,
      "warrior": 0,
      "systemShock": 65,
      "resurrection": 70,
      "poison": 0,
      "regen": null
    },
    {
      "min": 10,
      "max": 10,
      "hp": 0,
      "warrior": 0,
      "systemShock": 70,
      "resurrection": 75,
      "poison": 0,
      "regen": null
    },
    {
      "min": 11,
      "max": 11,
      "hp": 0,
      "warrior": 0,
      "systemShock": 75,
      "resurrection": 80,
      "poison": 0,
      "regen": null
    },
    {
      "min": 12,
      "max": 12,
      "hp": 0,
      "warrior": 0,
      "systemShock": 80,
      "resurrection": 85,
      "poison": 0,
      "regen": null
    },
    {
      "min": 13,
      "max": 13,
      "hp": 0,
      "warrior": 0,
      "systemShock": 85,
      "resurrection": 90,
      "poison": 0,
      "regen": null
    },
    {
      "min": 14,
      "max": 14,
      "hp": 0,
      "warrior": 0,
      "systemShock": 88,
      "resurrection": 92,
      "poison": 0,
      "regen": null
    },
    {
      "min": 15,
      "max": 15,
      "hp": 1,
      "warrior": 1,
      "systemShock": 90,
      "resurrection": 94,
      "poison": 0,
      "regen": null
    },
    {
      "min": 16,
      "max": 16,
      "hp": 2,
      "warrior": 2,
      "systemShock": 95,
      "resurrection": 96,
      "poison": 0,
      "regen": null
    },
    {
      "min": 17,
      "max": 17,
      "hp": 2,
      "warrior": 3,
      "systemShock": 97,
      "resurrection": 98,
      "poison": 0,
      "regen": null
    },
    {
      "min": 18,
      "max": 18,
      "hp": 2,
      "warrior": 4,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 0,
      "regen": null
    },
    {
      "min": 19,
      "max": 19,
      "hp": 2,
      "warrior": 5,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 1,
      "regen": null
    },
    {
      "min": 20,
      "max": 20,
      "hp": 2,
      "warrior": 5,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 1,
      "regen": {
        "hp": 1,
        "turns": 6
      }
    },
    {
      "min": 21,
      "max": 21,
      "hp": 2,
      "warrior": 6,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 2,
      "regen": {
        "hp": 1,
        "turns": 5
      }
    },
    {
      "min": 22,
      "max": 22,
      "hp": 2,
      "warrior": 6,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 2,
      "regen": {
        "hp": 1,
        "turns": 4
      }
    },
    {
      "min": 23,
      "max": 23,
      "hp": 2,
      "warrior": 6,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 3,
      "regen": {
        "hp": 1,
        "turns": 3
      }
    },
    {
      "min": 24,
      "max": 24,
      "hp": 2,
      "warrior": 7,
      "systemShock": 99,
      "resurrection": 100,
      "poison": 3,
      "regen": {
        "hp": 1,
        "turns": 2
      }
    },
    {
      "min": 25,
      "max": 25,
      "hp": 2,
      "warrior": 7,
      "systemShock": 100,
      "resurrection": 100,
      "poison": 4,
      "regen": {
        "hp": 1,
        "turns": 1
      }
    }
  ],
  "int": [
    {
      "min": 1,
      "max": 1,
      "languages": 0,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 2,
      "max": 2,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 3,
      "max": 3,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 4,
      "max": 4,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 5,
      "max": 5,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 6,
      "max": 6,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 7,
      "max": 7,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 8,
      "max": 8,
      "languages": 1,
      "maxSpellLevel": null,
      "learnSpell": null,
      "maxSpells": null,
      "illusionImmunity": null
    },
    {
      "min": 9,
      "max": 9,
      "languages": 2,
      "maxSpellLevel": 4,
      "learnSpell": 35,
      "maxSpells": 6,
      "illusionImmunity": null
    },
    {
      "min": 10,
      "max": 10,
      "languages": 2,
      "maxSpellLevel": 5,
      "learnSpell": 40,
      "maxSpells": 7,
      "illusionImmunity": null
    },
    {
      "min": 11,
      "max": 11,
      "languages": 2,
      "maxSpellLevel": 5,
      "learnSpell": 45,
      "maxSpells": 7,
      "illusionImmunity": null
    },
    {
      "min": 12,
      "max": 12,
      "languages": 3,
      "maxSpellLevel": 6,
      "learnSpell": 50,
      "maxSpells": 7,
      "illusionImmunity": null
    },
    {
      "min": 13,
      "max": 13,
      "languages": 3,
      "maxSpellLevel": 6,
      "learnSpell": 55,
      "maxSpells": 9,
      "illusionImmunity": null
    },
    {
      "min": 14,
      "max": 14,
      "languages": 4,
      "maxSpellLevel": 7,
      "learnSpell": 60,
      "maxSpells": 9,
      "illusionImmunity": null
    },
    {
      "min": 15,
      "max": 15,
      "languages": 4,
      "maxSpellLevel": 7,
      "learnSpell": 65,
      "maxSpells": 11,
      "illusionImmunity": null
    },
    {
      "min": 16,
      "max": 16,
      "languages": 5,
      "maxSpellLevel": 8,
      "learnSpell": 70,
      "maxSpells": 11,
      "illusionImmunity": null
    },
    {
      "min": 17,
      "max": 17,
      "languages": 6,
      "maxSpellLevel": 8,
      "learnSpell": 75,
      "maxSpells": 14,
      "illusionImmunity": null
    },
    {
      "min": 18,
      "max": 18,
      "languages": 7,
      "maxSpellLevel": 9,
      "learnSpell": 85,
      "maxSpells": 18,
      "illusionImmunity": null
    },
    {
      "min": 19,
      "max": 19,
      "languages": 8,
      "maxSpellLevel": 9,
      "learnSpell": 95,
      "maxSpells": "all",
      "illusionImmunity": 1
    },
    {
      "min": 20,
      "max": 20,
      "languages": 9,
      "maxSpellLevel": 9,
      "learnSpell": 96,
      "maxSpells": "all",
      "illusionImmunity": 2
    },
    {
      "min": 21,
      "max": 21,
      "languages": 10,
      "maxSpellLevel": 9,
      "learnSpell": 97,
      "maxSpells": "all",
      "illusionImmunity": 3
    },
    {
      "min": 22,
      "max": 22,
      "languages": 11,
      "maxSpellLevel": 9,
      "learnSpell": 98,
      "maxSpells": "all",
      "illusionImmunity": 4
    },
    {
      "min": 23,
      "max": 23,
      "languages": 12,
      "maxSpellLevel": 9,
      "learnSpell": 99,
      "maxSpells": "all",
      "illusionImmunity": 5
    },
    {
      "min": 24,
      "max": 24,
      "languages": 15,
      "maxSpellLevel": 9,
      "learnSpell": 100,
      "maxSpells": "all",
      "illusionImmunity": 6
    },
    {
      "min": 25,
      "max": 25,
      "languages": 20,
      "maxSpellLevel": 9,
      "learnSpell": 100,
      "maxSpells": "all",
      "illusionImmunity": 7
    }
  ],
  "wis": [
    {
      "min": 1,
      "max": 1,
      "magicDef": -6,
      "bonusSpells": [],
      "spellFailure": 80,
      "immunity": []
    },
    {
      "min": 2,
      "max": 2,
      "magicDef": -4,
      "bonusSpells": [],
      "spellFailure": 60,
      "immunity": []
    },
    {
      "min": 3,
      "max": 3,
      "magicDef": -3,
      "bonusSpells": [],
      "spellFailure": 50,
      "immunity": []
    },
    {
      "min": 4,
      "max": 4,
      "magicDef": -2,
      "bonusSpells": [],
      "spellFailure": 45,
      "immunity": []
    },
    {
      "min": 5,
      "max": 5,
      "magicDef": -1,
      "bonusSpells": [],
      "spellFailure": 40,
      "immunity": []
    },
    {
      "min": 6,
      "max": 6,
      "magicDef": -1,
      "bonusSpells": [],
      "spellFailure": 35,
      "immunity": []
    },
    {
      "min": 7,
      "max": 7,
      "magicDef": -1,
      "bonusSpells": [],
      "spellFailure": 30,
      "immunity": []
    },
    {
      "min": 8,
      "max": 8,
      "magicDef": 0,
      "bonusSpells": [],
      "spellFailure": 25,
      "immunity": []
    },
    {
      "min": 9,
      "max": 9,
      "magicDef": 0,
      "bonusSpells": [],
      "spellFailure": 20,
      "immunity": []
    },
    {
      "min": 10,
      "max": 10,
      "magicDef": 0,
      "bonusSpells": [],
      "spellFailure": 15,
      "immunity": []
    },
    {
      "min": 11,
      "max": 11,
      "magicDef": 0,
      "bonusSpells": [],
      "spellFailure": 10,
      "immunity": []
    },
    {
      "min": 12,
      "max": 12,
      "magicDef": 0,
      "bonusSpells": [],
      "spellFailure": 5,
      "immunity": []
    },
    {
      "min": 13,
      "max": 13,
      "magicDef": 0,
      "bonusSpells": [
        1
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 14,
      "max": 14,
      "magicDef": 0,
      "bonusSpells": [
        1
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 15,
      "max": 15,
      "magicDef": 1,
      "bonusSpells": [
        2
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 16,
      "max": 16,
      "magicDef": 2,
      "bonusSpells": [
        2
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 17,
      "max": 17,
      "magicDef": 3,
      "bonusSpells": [
        3
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 18,
      "max": 18,
      "magicDef": 4,
      "bonusSpells": [
        4
      ],
      "spellFailure": 0,
      "immunity": []
    },
    {
      "min": 19,
      "max": 19,
      "magicDef": 4,
      "bonusSpells": [
        1,
        3
      ],
      "spellFailure": 0,
      "immunity": [
        "Cause Fear",
        "Charm Person",
        "Command",
        "Friends",
        "Hypnotism"
      ]
    },
    {
      "min": 20,
      "max": 20,
      "magicDef": 4,
      "bonusSpells": [
        2,
        4
      ],
      "spellFailure": 0,
      "immunity": [
        "Forget",
        "Hold Person",
        "Ray of Enfeeblement",
        "Scare"
      ]
    },
    {
      "min": 21,
      "max": 21,
      "magicDef": 4,
      "bonusSpells": [
        3,
        5
      ],
      "spellFailure": 0,
      "immunity": [
        "Fear"
      ]
    },
    {
      "min": 22,
      "max": 22,
      "magicDef": 4,
      "bonusSpells": [
        4,
        5
      ],
      "spellFailure": 0,
      "immunity": [
        "Charm Monster",
        "Confusion",
        "Emotion",
        "Fumble",
        "Suggestion"
      ]
    },
    {
      "min": 23,
      "max": 23,
      "magicDef": 4,
      "bonusSpells": [
        1,
        6
      ],
      "spellFailure": 0,
      "immunity": [
        "Chaos",
        "Feeblemind",
        "Hold Monster",
        "Magic Jar",
        "Quest"
      ]
    },
    {
      "min": 24,
      "max": 24,
      "magicDef": 4,
      "bonusSpells": [
        5,
        6
      ],
      "spellFailure": 0,
      "immunity": [
        "Geas",
        "Mass Suggestion",
        "Rod of Rulership"
      ]
    },
    {
      "min": 25,
      "max": 25,
      "magicDef": 4,
      "bonusSpells": [
        6,
        7
      ],
      "spellFailure": 0,
      "immunity": [
        "Antipathy/Sympathy",
        "Death Spell",
        "Mass Charm"
      ]
    }
  ],
  "cha": [
    {
      "min": 1,
      "max": 1,
      "henchmen": 0,
      "loyalty": -8,
      "reaction": -7
    },
    {
      "min": 2,
      "max": 2,
      "henchmen": 1,
      "loyalty": -7,
      "reaction": -6
    },
    {
      "min": 3,
      "max": 3,
      "henchmen": 1,
      "loyalty": -6,
      "reaction": -5
    },
    {
      "min": 4,
      "max": 4,
      "henchmen": 1,
      "loyalty": -5,
      "reaction": -4
    },
    {
      "min": 5,
      "max": 5,
      "henchmen": 2,
      "loyalty": -4,
      "reaction": -3
    },
    {
      "min": 6,
      "max": 6,
      "henchmen": 2,
      "loyalty": -3,
      "reaction": -2
    },
    {
      "min": 7,
      "max": 7,
      "henchmen": 3,
      "loyalty": -2,
      "reaction": -1
    },
    {
      "min": 8,
      "max": 8,
      "henchmen": 3,
      "loyalty": -1,
      "reaction": 0
    },
    {
      "min": 9,
      "max": 9,
      "henchmen": 4,
      "loyalty": 0,
      "reaction": 0
    },
    {
      "min": 10,
      "max": 10,
      "henchmen": 4,
      "loyalty": 0,
      "reaction": 0
    },
    {
      "min": 11,
      "max": 11,
      "henchmen": 4,
      "loyalty": 0,
      "reaction": 0
    },
    {
      "min": 12,
      "max": 12,
      "henchmen": 5,
      "loyalty": 0,
      "reaction": 0
    },
    {
      "min": 13,
      "max": 13,
      "henchmen": 5,
      "loyalty": 0,
      "reaction": 1
    },
    {
      "min": 14,
      "max": 14,
      "henchmen": 6,
      "loyalty": 1,
      "reaction": 2
    },
    {
      "min": 15,
      "max": 15,
      "henchmen": 7,
      "loyalty": 3,
      "reaction": 3
    },
    {
      "min": 16,
      "max": 16,
      "henchmen": 8,
      "loyalty": 4,
      "reaction": 5
    },
    {
      "min": 17,
      "max": 17,
      "henchmen": 10,
      "loyalty": 6,
      "reaction": 6
    },
    {
      "min": 18,
      "max": 18,
      "henchmen": 15,
      "loyalty": 8,
      "reaction": 7
    },
    {
      "min": 19,
      "max": 19,
      "henchmen": 20,
      "loyalty": 10,
      "reaction": 8
    },
    {
      "min": 20,
      "max": 20,
      "henchmen": 25,
      "loyalty": 12,
      "reaction": 9
    },
    {
      "min": 21,
      "max": 21,
      "henchmen": 30,
      "loyalty": 14,
      "reaction": 10
    },
    {
      "min": 22,
      "max": 22,
      "henchmen": 35,
      "loyalty": 16,
      "reaction": 11
    },
    {
      "min": 23,
      "max": 23,
      "henchmen": 40,
      "loyalty": 18,
      "reaction": 12
    },
    {
      "min": 24,
      "max": 24,
      "henchmen": 45,
      "loyalty": 20,
      "reaction": 13
    },
    {
      "min": 25,
      "max": 25,
      "henchmen": 50,
      "loyalty": 20,
      "reaction": 14
    }
  ]
};
