/**
 * GENERATED by tools/build-aq-equipment-data.py - do not edit by hand.
 *   Heat penalty for worn armour: https://adnd2e.fandom.com/wiki/Armor_in_Fiery_Zakhara_(AA) (revision 272178), Table 6
 */
export const AQ_TABLES = {"heat": {"maxAc": 7, "perClass": -1, "exempt": ["buckler", "daraq"]}};
