/**
 * GENERATED by tools/build-class-data.py - do not edit by hand.
 * PHB classes (Table 13 minimums, Table 22 specialists) and Complete Handbook kits,
 * from the AD&D 2e fandom wiki. Mechanical facts and links only; verify against the books.
 *   Table 13: https://adnd2e.fandom.com/wiki/Character_Race_Tables_(PHB) (revision 167919)
 *   Table 22: https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB) (revision 158095)
 *   Kits: one wiki page each (url + revid per entry).
 */
export const CLASSES = {
  "fighter": {
    "name": "Fighter",
    "group": "warrior",
    "min": {
      "str": 9
    },
    "prime": [
      "str"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Fighter_(PHB)"
  },
  "paladin": {
    "name": "Paladin",
    "group": "warrior",
    "min": {
      "str": 12,
      "con": 9,
      "wis": 13,
      "cha": 17
    },
    "prime": [
      "str",
      "cha"
    ],
    "alignments": [
      "lg"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Paladin_(PHB)"
  },
  "ranger": {
    "name": "Ranger",
    "group": "warrior",
    "min": {
      "str": 13,
      "dex": 13,
      "con": 14,
      "wis": 14
    },
    "prime": [
      "str",
      "dex",
      "wis"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Ranger_(PHB)"
  },
  "mage": {
    "name": "Mage",
    "group": "wizard",
    "min": {
      "int": 9
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Mage_(PHB)"
  },
  "cleric": {
    "name": "Cleric",
    "group": "priest",
    "min": {
      "wis": 9
    },
    "prime": [
      "wis"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Cleric_(PHB)"
  },
  "druid": {
    "name": "Druid",
    "group": "priest",
    "min": {
      "wis": 12,
      "cha": 15
    },
    "prime": [
      "wis",
      "cha"
    ],
    "alignments": [
      "n"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Druid_(PHB)"
  },
  "thief": {
    "name": "Thief",
    "group": "rogue",
    "min": {
      "dex": 9
    },
    "prime": [
      "dex"
    ],
    "alignments": [
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Thief_(PHB)"
  },
  "bard": {
    "name": "Bard",
    "group": "rogue",
    "min": {
      "dex": 12,
      "int": 13,
      "cha": 15
    },
    "prime": [
      "dex",
      "cha"
    ],
    "alignments": [
      "ng",
      "ln",
      "n",
      "cn",
      "ne"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Bard_(PHB)"
  },
  "abjurer": {
    "name": "Abjurer",
    "group": "wizard",
    "min": {
      "int": 9,
      "wis": 15
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Abjuration",
    "opposition": "Alteration & Illusion",
    "races": [
      "human"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "conjurer": {
    "name": "Conjurer",
    "group": "wizard",
    "min": {
      "int": 9,
      "con": 15
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Conj./Summ.",
    "opposition": "Gr. Divin. & Invocation",
    "races": [
      "human",
      "half-elf"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "diviner": {
    "name": "Diviner",
    "group": "wizard",
    "min": {
      "int": 9,
      "wis": 16
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Gr. Divin.",
    "opposition": "Conj./Summ.",
    "races": [
      "human",
      "half-elf",
      "elf"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "enchanter": {
    "name": "Enchanter",
    "group": "wizard",
    "min": {
      "int": 9,
      "cha": 16
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Ench./Charm",
    "opposition": "Invoc./Evoc. & Necromancy",
    "races": [
      "human",
      "half-elf",
      "elf"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "illusionist": {
    "name": "Illusionist",
    "group": "wizard",
    "min": {
      "int": 9,
      "dex": 16
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Illusion",
    "opposition": "Necro., Invoc./Evoc., Abjur.",
    "races": [
      "human",
      "gnome"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "invoker": {
    "name": "Invoker",
    "group": "wizard",
    "min": {
      "int": 9,
      "con": 16
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Invoc./Evoc.",
    "opposition": "Ench./Charm Conj./Summ.",
    "races": [
      "human"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "necromancer": {
    "name": "Necromancer",
    "group": "wizard",
    "min": {
      "int": 9,
      "wis": 16
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Necromancy",
    "opposition": "Illusion & Ench./Charm",
    "races": [
      "human"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  },
  "transmuter": {
    "name": "Transmuter",
    "group": "wizard",
    "min": {
      "int": 9,
      "dex": 15
    },
    "prime": [
      "int"
    ],
    "alignments": [
      "lg",
      "ng",
      "cg",
      "ln",
      "n",
      "cn",
      "le",
      "ne",
      "ce"
    ],
    "school": "Alteration",
    "opposition": "Abjuration & Necromancy",
    "races": [
      "human",
      "half-elf"
    ],
    "url": "https://adnd2e.fandom.com/wiki/Specialist_Wizard_(PHB)"
  }
};

export const KITS = {
  "academician": {
    "name": "Academician",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "int": 13,
      "wis": 11
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Academician_(Character_Kit)",
    "revid": 167177
  },
  "acrobat-thief": {
    "name": "Acrobat",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 12,
      "dex": 14
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Acrobat_-_Thief_(Character_Kit)",
    "revid": 153298
  },
  "adventurer": {
    "name": "Adventurer",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Adventurer_(Character_Kit)",
    "revid": 153299
  },
  "amazon-fighter": {
    "name": "Amazon",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Amazon_-_Fighter_(Character_Kit)",
    "revid": 153537
  },
  "amazon-priestess": {
    "name": "Amazon Priestess",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Amazon_Priestess_(Character_Kit)",
    "revid": 153306
  },
  "amazon-sorceress": {
    "name": "Amazon Sorceress",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Amazon_Sorceress_(Character_Kit)",
    "revid": 153307
  },
  "anagakok": {
    "name": "Anagakok",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Anagakok_(Character_Kit)",
    "revid": 248775
  },
  "assassin-thief": {
    "name": "Assassin",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 12,
      "dex": 12,
      "int": 11
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Assassin_-_Thief_(Character_Kit)",
    "revid": 272122
  },
  "bandit": {
    "name": "Bandit",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 10,
      "con": 10
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Bandit_(Character_Kit)",
    "revid": 276937
  },
  "barbarian-fighter": {
    "name": "Barbarian",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Barbarian_-_Fighter_(Character_Kit)",
    "revid": 153538
  },
  "barbarian-berserker-priest": {
    "name": "Barbarian/Berserker Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Barbarian/Berserker_Priest_(Character_Kit)",
    "revid": 153321
  },
  "beast-rider": {
    "name": "Beast-Rider",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "cha": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Beast-Rider_(Character_Kit)",
    "revid": 153539
  },
  "beastmaster-ranger": {
    "name": "Beastmaster",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Beastmaster_-_Ranger_(Character_Kit)",
    "revid": 147957
  },
  "beggar-thief": {
    "name": "Beggar",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Beggar_-_Thief_(Character_Kit)",
    "revid": 271756
  },
  "berserker": {
    "name": "Berserker",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Berserker_(Character_Kit)",
    "revid": 171344
  },
  "blade": {
    "name": "Blade",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "dex": 13,
      "int": 13,
      "cha": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Blade_(Character_Kit)",
    "revid": 144925
  },
  "bounty-hunter": {
    "name": "Bounty Hunter",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 11,
      "dex": 11,
      "con": 11,
      "int": 11,
      "wis": 11
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Bounty_Hunter_(Character_Kit)",
    "revid": 153333
  },
  "buccaneer": {
    "name": "Buccaneer",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "con": 10
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Buccaneer_(Character_Kit)",
    "revid": 153335
  },
  "burglar": {
    "name": "Burglar",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 10,
      "dex": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Burglar_(Character_Kit)",
    "revid": 153336
  },
  "cavalier-fighter": {
    "name": "Cavalier",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 15,
      "dex": 15,
      "con": 15,
      "int": 10,
      "wis": 10
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Cavalier_-_Fighter_(Character_Kit)",
    "revid": 171846
  },
  "charlatan": {
    "name": "Charlatan",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Charlatan_(Character_Kit)",
    "revid": 271518
  },
  "chevalier": {
    "name": "Chevalier",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Chevalier_(Character_Kit)",
    "revid": 146446
  },
  "cutpurse": {
    "name": "Cutpurse",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Cutpurse_(Character_Kit)",
    "revid": 153348
  },
  "divinate": {
    "name": "Divinate",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Divinate_(Character_Kit)",
    "revid": 276421
  },
  "dwarven-chanter": {
    "name": "Dwarven Chanter",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "con": 13,
      "int": 0
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Dwarven_Chanter_(Character_Kit)",
    "revid": 171882
  },
  "elven-minstrel": {
    "name": "Elven Minstrel",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Elven_Minstrel_(Character_Kit)",
    "revid": 148813
  },
  "envoy": {
    "name": "Envoy",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "int": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Envoy_(Character_Kit)",
    "revid": 146454
  },
  "equerry": {
    "name": "Equerry",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "wis": 14
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Equerry_(Character_Kit)",
    "revid": 157730
  },
  "errant": {
    "name": "Errant",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Errant_(Character_Kit)",
    "revid": 146457
  },
  "expatriate": {
    "name": "Expatriate",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Expatriate_(Character_Kit)",
    "revid": 146458
  },
  "explorer-ranger": {
    "name": "Explorer",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "int": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Explorer_-_Ranger_(Character_Kit)",
    "revid": 272391
  },
  "falconer": {
    "name": "Falconer",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Falconer_(Character_Kit)",
    "revid": 151347
  },
  "fence": {
    "name": "Fence",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "int": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Fence_(Character_Kit)",
    "revid": 153368
  },
  "feralan": {
    "name": "Feralan",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "con": 15,
      "str": 14
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Feralan_(Character_Kit)",
    "revid": 157744
  },
  "fighting-monk": {
    "name": "Fighting-Monk",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {
      "dex": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Fighting-Monk_(Character_Kit)",
    "revid": 153371
  },
  "forest-runner": {
    "name": "Forest Runner",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "cha": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Forest_Runner_(Character_Kit)",
    "revid": 145325
  },
  "gallant": {
    "name": "Gallant",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Gallant_(Character_Kit)",
    "revid": 144927
  },
  "ghosthunter": {
    "name": "Ghosthunter",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Ghosthunter_(Character_Kit)",
    "revid": 157766
  },
  "giant-killer": {
    "name": "Giant Killer",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "str": 15,
      "dex": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Giant_Killer_(Character_Kit)",
    "revid": 145333
  },
  "gladiator-fighter": {
    "name": "Gladiator",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Gladiator_-_Fighter_(Character_Kit)",
    "revid": 153376
  },
  "gnome-professor": {
    "name": "Gnome Professor",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "int": 15,
      "cha": 13
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Gnome_Professor_(Character_Kit)",
    "revid": 151359
  },
  "greenwood-ranger": {
    "name": "Greenwood Ranger",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Greenwood_Ranger_(Character_Kit)",
    "revid": 153379
  },
  "guardian-ranger": {
    "name": "Guardian",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Guardian_-_Ranger_(Character_Kit)",
    "revid": 145346
  },
  "gypsy-bard": {
    "name": "Gypsy-bard",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Gypsy-bard_(Character_Kit)",
    "revid": 277601
  },
  "halfling-whistler": {
    "name": "Halfling Whistler",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "wis": 13,
      "int": 10
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Halfling_Whistler_(Character_Kit)",
    "revid": 144947
  },
  "herald": {
    "name": "Herald",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Herald_(Character_Kit)",
    "revid": 144929
  },
  "inquisitor": {
    "name": "Inquisitor",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "int": 11
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Inquisitor_(Character_Kit)",
    "revid": 146475
  },
  "investigator-thief": {
    "name": "Investigator",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Investigator_-_Thief_(Character_Kit)",
    "revid": 142964
  },
  "jester-bard": {
    "name": "Jester",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "dex": 14
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Jester_-_Bard_(Character_Kit)",
    "revid": 271853
  },
  "jongleur": {
    "name": "Jongleur",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "dex": 14
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Jongleur_(Character_Kit)",
    "revid": 151377
  },
  "justifier": {
    "name": "Justifier",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "str": 14,
      "dex": 14
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Justifier_(Character_Kit)",
    "revid": 157836
  },
  "loremaster": {
    "name": "Loremaster",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "int": 14,
      "wis": 14
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Loremaster_(Character_Kit)",
    "revid": 144932
  },
  "medician": {
    "name": "Medician",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "int": 10
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Medician_(Character_Kit)",
    "revid": 146477
  },
  "meistersinger": {
    "name": "Meistersinger",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Meistersinger_(Character_Kit)",
    "revid": 144933
  },
  "militant-wizard": {
    "name": "Militant Wizard",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "str": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Militant_Wizard_(Character_Kit)",
    "revid": 153410
  },
  "militarist": {
    "name": "Militarist",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "dex": 12,
      "con": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Militarist_(Character_Kit)",
    "revid": 146481
  },
  "mountain-man": {
    "name": "Mountain Man",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "str": 14,
      "con": 15
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Mountain_Man_(Character_Kit)",
    "revid": 157911
  },
  "myrmidon": {
    "name": "Myrmidon",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 12,
      "con": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Myrmidon_(Character_Kit)",
    "revid": 153572
  },
  "mystic-wizard": {
    "name": "Mystic",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "wis": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Mystic_-_Wizard_(Character_Kit)",
    "revid": 271865
  },
  "noble-warrior": {
    "name": "Noble Warrior",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 13,
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Noble_Warrior_(Character_Kit)",
    "revid": 153573
  },
  "nobleman-priest": {
    "name": "Nobleman Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Nobleman_Priest_(Character_Kit)",
    "revid": 153422
  },
  "outlaw-priest": {
    "name": "Outlaw Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Outlaw_Priest_(Character_Kit)",
    "revid": 264932
  },
  "pacifist-priest": {
    "name": "Pacifist Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Pacifist_Priest_(Character_Kit)",
    "revid": 153431
  },
  "pathfinder-ranger": {
    "name": "Pathfinder",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Pathfinder_-_Ranger_(Character_Kit)",
    "revid": 272394
  },
  "patrician-wizard": {
    "name": "Patrician",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Patrician_-_Wizard_(Character_Kit)",
    "revid": 264974
  },
  "peasant-hero-fighter": {
    "name": "Peasant Hero",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Peasant_Hero_-_Fighter_(Character_Kit)",
    "revid": 153434
  },
  "peasant-priest": {
    "name": "Peasant Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Peasant_Priest_(Character_Kit)",
    "revid": 153435
  },
  "peasant-wizard": {
    "name": "Peasant Wizard",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Peasant_Wizard_(Character_Kit)",
    "revid": 142565
  },
  "pirate-outlaw": {
    "name": "Pirate/Outlaw",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Pirate/Outlaw_(Character_Kit)",
    "revid": 264930
  },
  "prophet-priest": {
    "name": "Prophet Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {
      "wis": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Prophet_Priest_(Character_Kit)",
    "revid": 153443
  },
  "riddlemaster": {
    "name": "Riddlemaster",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {
      "int": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Riddlemaster_(Character_Kit)",
    "revid": 151441
  },
  "samurai-fighter": {
    "name": "Samurai",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 13,
      "wis": 13,
      "con": 13,
      "int": 14
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Samurai_-_Fighter_(Character_Kit)",
    "revid": 153582
  },
  "savage-fighter": {
    "name": "Savage",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "str": 11,
      "con": 15
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Savage_-_Fighter_(Character_Kit)",
    "revid": 271885
  },
  "savage-priest": {
    "name": "Savage Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {
      "str": 11,
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Savage_Priest_(Character_Kit)",
    "revid": 153457
  },
  "savage-wizard": {
    "name": "Savage Wizard",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "str": 11,
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Savage_Wizard_(Character_Kit)",
    "revid": 142569
  },
  "scholar-priest": {
    "name": "Scholar Priest",
    "classes": [
      "cleric",
      "druid"
    ],
    "source": "Complete Priest's Handbook",
    "min": {
      "int": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Scholar_Priest_(Character_Kit)",
    "revid": 153460
  },
  "scout-thief": {
    "name": "Scout",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Scout_-_Thief_(Character_Kit)",
    "revid": 153461
  },
  "sea-ranger": {
    "name": "Sea Ranger",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "int": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Sea_Ranger_(Character_Kit)",
    "revid": 151454
  },
  "seeker": {
    "name": "Seeker",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "wis": 15
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Seeker_(Character_Kit)",
    "revid": 158066
  },
  "skald": {
    "name": "Skald",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Skald_(Character_Kit)",
    "revid": 144921
  },
  "skyrider": {
    "name": "Skyrider",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Skyrider_(Character_Kit)",
    "revid": 146484
  },
  "smuggler-thief": {
    "name": "Smuggler",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Smuggler_-_Thief_(Character_Kit)",
    "revid": 153476
  },
  "spy-thief": {
    "name": "Spy",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "int": 11
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Spy_-_Thief_(Character_Kit)",
    "revid": 153482
  },
  "squire-paladin": {
    "name": "Squire",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Squire_-_Paladin_(Character_Kit)",
    "revid": 146492
  },
  "stalker-ranger": {
    "name": "Stalker",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "int": 14
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Stalker_-_Ranger_(Character_Kit)",
    "revid": 272401
  },
  "swashbuckler-fighter": {
    "name": "Swashbuckler",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "int": 13,
      "dex": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Swashbuckler_-_Fighter_(Character_Kit)",
    "revid": 271905
  },
  "swashbuckler-thief": {
    "name": "Swashbuckler",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "str": 13,
      "dex": 13,
      "int": 13,
      "cha": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Swashbuckler_-_Thief_(Character_Kit)",
    "revid": 271906
  },
  "swindler": {
    "name": "Swindler",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {
      "cha": 12
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Swindler_(Character_Kit)",
    "revid": 153489
  },
  "thespian": {
    "name": "Thespian",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Thespian_(Character_Kit)",
    "revid": 144923
  },
  "thug-thief": {
    "name": "Thug",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Thug_-_Thief_(Character_Kit)",
    "revid": 271910
  },
  "troubleshooter": {
    "name": "Troubleshooter",
    "classes": [
      "thief"
    ],
    "source": "Complete Thief's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Troubleshooter_(Character_Kit)",
    "revid": 153501
  },
  "true-bard": {
    "name": "True Bard",
    "classes": [
      "bard"
    ],
    "source": "Complete Bard's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/True_Bard_(Character_Kit)",
    "revid": 144924
  },
  "true-paladin": {
    "name": "True Paladin",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/True_Paladin_(Character_Kit)",
    "revid": 146444
  },
  "votary": {
    "name": "Votary",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {},
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Votary_(Character_Kit)",
    "revid": 158204
  },
  "warden": {
    "name": "Warden",
    "classes": [
      "ranger"
    ],
    "source": "Complete Ranger's Handbook",
    "min": {
      "cha": 12
    },
    "otherRequirements": true,
    "url": "https://adnd2e.fandom.com/wiki/Warden_(Character_Kit)",
    "revid": 153510
  },
  "wilderness-warrior": {
    "name": "Wilderness Warrior",
    "classes": [
      "fighter"
    ],
    "source": "Complete Fighter's Handbook",
    "min": {
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Wilderness_Warrior_(Character_Kit)",
    "revid": 153514
  },
  "witch": {
    "name": "Witch",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "int": 13,
      "wis": 13,
      "con": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Witch_(Character_Kit)",
    "revid": 142584
  },
  "wu-jen": {
    "name": "Wu Jen",
    "classes": [
      "mage",
      "abjurer",
      "conjurer",
      "diviner",
      "enchanter",
      "illusionist",
      "invoker",
      "necromancer",
      "transmuter"
    ],
    "source": "Complete Wizard's Handbook",
    "min": {
      "int": 13
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Wu_Jen_(Character_Kit)",
    "revid": 278338
  },
  "wyrmslayer": {
    "name": "Wyrmslayer",
    "classes": [
      "paladin"
    ],
    "source": "Complete Paladin's Handbook",
    "min": {
      "str": 14,
      "dex": 10,
      "con": 10
    },
    "otherRequirements": false,
    "url": "https://adnd2e.fandom.com/wiki/Wyrmslayer_(Character_Kit)",
    "revid": 146520
  }
};
