/**
 * GENERATED by tools/build-hireling-data.py - do not edit by hand.
 * Find Familiar (Wizard Spell): https://adnd2e.fandom.com/wiki/Find_Familiar_(Wizard_Spell) (revision 267861).
 * rows: the d20 table (key "" = no familiar); rules: hit points, AC, surprise bonus, daily loss when apart,
 * Constitution loss on its death, command range, once per year, casting time, material cost.
 */
export const FAMILIAR_TABLES = {"rows": [{"min": 1, "max": 5, "name": "Cat, black", "senses": "Excellent night vision & superior hearing", "key": "cat-black"}, {"min": 6, "max": 7, "name": "Crow", "senses": "Excellent vision", "key": "crow"}, {"min": 8, "max": 9, "name": "Hawk", "senses": "Very superior distance vision", "key": "hawk"}, {"min": 10, "max": 11, "name": "Owl", "senses": "Night vision equals human daylight vision, superior hearing", "key": "owl"}, {"min": 12, "max": 13, "name": "Toad", "senses": "Wide-angle vision", "key": "toad"}, {"min": 14, "max": 15, "name": "Weasel", "senses": "Superior hearing & very superior olfactory power", "key": "weasel"}, {"min": 16, "max": 20, "name": "", "senses": "No familiar available within spell range", "key": ""}], "rules": {"hp": {"dice": "1d3+1", "perLevel": 1}, "ac": 7, "surprise": 1, "separatedLoss": 1, "conLoss": 1, "range": "1 mile", "onceYear": true, "castingTime": "2d12", "cost": "1,000 gp", "contact": {"saved": 0, "failed": 0.5}}};
