/**
 * GENERATED by tools/build-monster-data.py - do not edit by hand.
 * DMG Table 39 (Creature THAC0): https://adnd2e.fandom.com/wiki/Calculating_THAC0_(DMG) (revision 144992).
 * Index 0 = less than one Hit Die; index n = n Hit Dice ("n+"); the last entry covers 16 and more.
 */
export const CREATURE_THAC0 = [20, 19, 19, 17, 17, 15, 15, 13, 13, 11, 11, 9, 9, 7, 7, 5, 5];
