/**
 * GENERATED by tools/build-movement-tables.py - do not edit by hand.
 * PHB Tables 47 and 48: https://adnd2e.fandom.com/wiki/Encumbrance_Tables_(PHB) (revision 157728)
 * PHB Table 64: https://adnd2e.fandom.com/wiki/Movement_(PHB) (revision 262232)
 * Strength key: score * 100 + exceptional percentile (18/01 = 1801, 18/00 = 1900).
 */
/** Table 47: upper weight (lb) of Unencumbered, Light, Moderate, Heavy, Severe; most weight that can be carried. */
export const ENCUMBRANCE_TABLE = [{"min": 200, "max": 200, "limits": [1, 2, 3, 4, 6], "maxCarried": 6}, {"min": 300, "max": 300, "limits": [5, 6, 7, 9, 10], "maxCarried": 10}, {"min": 400, "max": 500, "limits": [10, 13, 16, 19, 25], "maxCarried": 25}, {"min": 600, "max": 700, "limits": [20, 29, 38, 46, 55], "maxCarried": 55}, {"min": 800, "max": 900, "limits": [35, 50, 65, 80, 90], "maxCarried": 90}, {"min": 1000, "max": 1100, "limits": [40, 58, 76, 96, 110], "maxCarried": 110}, {"min": 1200, "max": 1300, "limits": [45, 69, 93, 117, 140], "maxCarried": 140}, {"min": 1400, "max": 1500, "limits": [55, 85, 115, 145, 170], "maxCarried": 170}, {"min": 1600, "max": 1600, "limits": [70, 100, 130, 160, 195], "maxCarried": 195}, {"min": 1700, "max": 1700, "limits": [85, 121, 157, 193, 220], "maxCarried": 220}, {"min": 1800, "max": 1800, "limits": [110, 149, 188, 227, 255], "maxCarried": 255}, {"min": 1801, "max": 1850, "limits": [135, 174, 213, 252, 280], "maxCarried": 280}, {"min": 1851, "max": 1875, "limits": [160, 199, 238, 277, 305], "maxCarried": 305}, {"min": 1876, "max": 1890, "limits": [185, 224, 263, 302, 330], "maxCarried": 330}, {"min": 1891, "max": 1899, "limits": [235, 274, 313, 352, 380], "maxCarried": 380}, {"min": 1900, "max": 1900, "limits": [335, 374, 413, 452, 480], "maxCarried": 480}];

/** Table 48: per Strength, the most weight (lb) for each modified movement rate (rates12 / rates6 by base move). */
export const MOVEMENT_TABLE = {"rates12": [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1], "rates6": [6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1, 1], "rows": [{"min": 200, "max": 200, "loads": [1, null, 2, null, null, 3, null, null, 4, null, null, 5]}, {"min": 300, "max": 300, "loads": [5, null, 6, null, 7, null, null, 8, null, 9, null, null]}, {"min": 400, "max": 500, "loads": [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]}, {"min": 600, "max": 700, "loads": [20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53]}, {"min": 800, "max": 900, "loads": [35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 89]}, {"min": 1000, "max": 1100, "loads": [40, 46, 52, 58, 64, 70, 76, 82, 88, 94, 100, 106]}, {"min": 1200, "max": 1300, "loads": [45, 53, 61, 69, 77, 85, 93, 101, 109, 117, 125, 133]}, {"min": 1400, "max": 1500, "loads": [55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165]}, {"min": 1600, "max": 1600, "loads": [70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180]}, {"min": 1700, "max": 1700, "loads": [85, 97, 109, 121, 133, 145, 157, 169, 181, 193, 205, 217]}, {"min": 1800, "max": 1800, "loads": [110, 123, 136, 149, 162, 175, 188, 201, 214, 227, 240, 253]}, {"min": 1801, "max": 1850, "loads": [135, 148, 161, 174, 187, 200, 213, 226, 239, 252, 265, 278]}, {"min": 1851, "max": 1875, "loads": [160, 173, 186, 199, 212, 225, 238, 251, 264, 277, 290, 303]}, {"min": 1876, "max": 1890, "loads": [185, 198, 211, 224, 237, 250, 263, 276, 289, 302, 315, 328]}, {"min": 1891, "max": 1899, "loads": [235, 248, 261, 274, 287, 300, 313, 326, 339, 352, 365, 378]}, {"min": 1900, "max": 1900, "loads": [335, 348, 361, 374, 387, 400, 413, 426, 439, 452, 465, 478]}]};

/** Table 64: base movement rate per race identifier. */
export const BASE_MOVEMENT = {"human": 12, "dwarf": 6, "elf": 12, "half-elf": 12, "gnome": 6, "halfling": 6};

/** Table 42 (https://adnd2e.fandom.com/wiki/Money_and_Equipment_(PHB) rev 283165): coin value in copper pieces. */
export const COIN_VALUES = {"cp": 1, "sp": 10, "ep": 50, "gp": 100, "pp": 500};

/** Pushing a mount (https://adnd2e.fandom.com/wiki/Movement_(DMG) rev 262233): save vs. death (par) at double/triple speed. */
export const MOUNT_PUSH = {"save": "par", "double": {"factor": 2, "mod": 0, "perDay": -1, "lameRestDays": 1}, "triple": {"factor": 3, "mod": -3, "rest": "1d3"}, "hardy": {"identifiers": ["pony", "mule", "donkey"], "double": 2}};

/** Coins per pound, any metal (https://adnd2e.fandom.com/wiki/Treasure_Tables_(DMG) rev 158183). */
export const COINS_PER_POUND = 50;
