/**
 * GENERATED by tools/build-proficiency-data.py - do not edit by hand.
 * PHB Table 34 (proficiency slots) and Table 38 (nonweapon proficiency groups per class), from
 *   https://adnd2e.fandom.com/wiki/Proficiencies_(PHB) (revision 239783)
 *   https://adnd2e.fandom.com/wiki/Nonweapon_Proficiencies_Tables_(PHB) (revision 260489)
 * A new slot is gained at every level evenly divisible by the rate; nonweapon proficiencies from
 * a group outside the class's groups cost one additional slot.
 */
export const PROFICIENCY_SLOTS = {
  "priest": {
    "weaponInitial": 2,
    "weaponRate": 4,
    "penalty": -3,
    "nonweaponInitial": 4,
    "nonweaponRate": 3
  },
  "rogue": {
    "weaponInitial": 2,
    "weaponRate": 4,
    "penalty": -3,
    "nonweaponInitial": 3,
    "nonweaponRate": 4
  },
  "warrior": {
    "weaponInitial": 4,
    "weaponRate": 3,
    "penalty": -2,
    "nonweaponInitial": 3,
    "nonweaponRate": 3
  },
  "wizard": {
    "weaponInitial": 1,
    "weaponRate": 6,
    "penalty": -5,
    "nonweaponInitial": 4,
    "nonweaponRate": 3
  }
};

export const PROFICIENCY_GROUPS = {
  "fighter": [
    "warrior",
    "general"
  ],
  "paladin": [
    "warrior",
    "priest",
    "general"
  ],
  "ranger": [
    "warrior",
    "wizard",
    "general"
  ],
  "cleric": [
    "priest",
    "general"
  ],
  "druid": [
    "priest",
    "warrior",
    "general"
  ],
  "mage": [
    "wizard",
    "general"
  ],
  "illusionist": [
    "wizard",
    "general"
  ],
  "thief": [
    "rogue",
    "general"
  ],
  "bard": [
    "rogue",
    "warrior",
    "wizard",
    "general"
  ],
  "abjurer": [
    "wizard",
    "general"
  ],
  "conjurer": [
    "wizard",
    "general"
  ],
  "diviner": [
    "wizard",
    "general"
  ],
  "enchanter": [
    "wizard",
    "general"
  ],
  "invoker": [
    "wizard",
    "general"
  ],
  "necromancer": [
    "wizard",
    "general"
  ],
  "transmuter": [
    "wizard",
    "general"
  ]
};
