/**
 * GENERATED by tools/build-race-data.py - do not edit by hand.
 * PHB Table 9: Constitution Saving Throw Bonuses (dwarves, gnomes, halflings), from
 *   https://adnd2e.fandom.com/wiki/Character_Race_Tables_(PHB) (revision 167919)
 * Applies to saves vs. rod/staff/wand and spells; dwarves and halflings also vs. poison.
 */
export const CON_SAVE_BONUS = [{"min": 4, "max": 6, "bonus": 1}, {"min": 7, "max": 10, "bonus": 2}, {"min": 11, "max": 13, "bonus": 3}, {"min": 14, "max": 17, "bonus": 4}, {"min": 18, "max": 19, "bonus": 5}];
