/**
 * GENERATED by tools/build-shair-tables.py - do not edit by hand.
 * Requesting a Spell (AA): https://adnd2e.fandom.com/wiki/Requesting_a_Spell_(AA) (revision 272246).
 * Summoning a Familiar (AA): https://adnd2e.fandom.com/wiki/Summoning_a_Familiar_(AA) (revision 272255).
 * Sha'ir (Character Kit): https://adnd2e.fandom.com/wiki/Sha'ir_(Character_Kit) (revision 272249).
 * A sha'ir's gen fetching spells: search time, chance of success, priest spells. unitSeconds: The Combat Round (PHB).
 */
export const SHAIR = {"sources": {"Requesting a Spell (AA)": {"url": "https://adnd2e.fandom.com/wiki/Requesting_a_Spell_(AA)", "revision": 272246}, "Summoning a Familiar (AA)": {"url": "https://adnd2e.fandom.com/wiki/Summoning_a_Familiar_(AA)", "revision": 272255}, "Sha'ir (Character Kit)": {"url": "https://adnd2e.fandom.com/wiki/Sha'ir_(Character_Kit)", "revision": 272249}}, "unitSeconds": {"round": 60, "turn": 600, "hour": 3600}, "searchNative": {"unit": "round", "die": "1d6", "perLevel": 1}, "searchHigh": {"unit": "turn", "die": "1d6", "perLevel": 1}, "searchForeign": {"unit": "hour", "die": "1d6", "perLevel": 1}, "base": {"chance": 50, "failAt": 90}, "perShairLevel": 5, "perSpellLevel": -10, "generalKnowledge": 10, "foreignOrPriest": -30, "repeat": -10, "repeatWindow": 86400, "delay00": "1d10", "castWithin": 3, "oneAtATime": true, "priestNotice": 10, "replacementDelay": 1, "commonLevels": 2, "raceFailure": {"dwarf": 20}};
