#!/usr/bin/env python3
"""Generate module/rules/ability-tables.mjs from the AD&D 2e fandom wiki ability tables.

Fetches wikitext through the MediaWiki API (the HTML pages sit behind a JS challenge),
parses the numeric table data only, and writes an ES module. Run from the repo root:
    python3 tools/build-ability-tables.py
"""
import json, re, urllib.request

API = "https://adnd2e.fandom.com/api.php?action=parse&page={}&prop=wikitext|revid&format=json"
PAGES = {"str": "Strength_(PHB)", "dex": "Dexterity_(PHB)", "con": "Constitution_(PHB)",
         "int": "Intelligence", "wis": "Wisdom_(PHB)", "cha": "Charisma_(PHB)"}


def fetch(page):
    req = urllib.request.Request(API.format(page), headers={"User-Agent": "coldhobbits-ad2e-table-builder"})
    with urllib.request.urlopen(req) as r:
        d = json.load(r)["parse"]
    return d["wikitext"]["*"], d["revid"]


def clean(c):
    c = re.sub(r"\{\{frac\|(\d+)\|(\d+)\}\}", r"\1/\2", c)
    c = re.sub(r"\{\{br\}\}|<br\s*/?>", " ", c, flags=re.I)
    c = re.sub(r"\[\[(?:[^|\]]*\|)?([^\]]*)\]\]", r"\1", c)
    c = re.sub(r"<[^>]+>|'''?", "", c)
    if "scope=" in c:
        c = c.split("|", 1)[1]
    return c.strip()


def first_table(wiki):
    """Rows of the first article-table; handles both one-cell-per-line and `||` rows."""
    t = re.search(r"\{\|[^\n]*article-table.*?\n\|\}", wiki, flags=re.S).group(0)
    rows = []
    for chunk in re.split(r"\n\|-", t)[1:]:
        lines = [l for l in chunk.split("\n") if l.startswith("|") and not l.startswith(("|}", "|+"))]
        cells = []
        for l in lines:
            cells += [clean(x) for x in l[1:].split("||")]
        if cells:
            rows.append(cells)
    return rows


def num(v):
    v = v.replace(",", "").replace("%", "").strip()
    if v in ("Normal", "None", "nil", "—", ""):
        return 0
    return int(v)


def score_range(s):
    a, _, b = s.partition("-")
    return int(a), int(b or a)


def ordinal(v):
    m = re.match(r"(\d+)", v.strip())
    return int(m.group(1)) if m else None


def build():
    src, out = {}, {}
    wiki = {}
    for k, p in PAGES.items():
        wiki[k], rev = fetch(p)
        src[k] = {"page": "https://adnd2e.fandom.com/wiki/" + p, "revid": rev}

    str_rows, str_exc = [], []
    for r in first_table(wiki["str"]):
        doors = re.match(r"(\d+)(?:\((\d+)\))?", r[5])
        row = {"hit": num(r[1]), "dmg": num(r[2]), "weight": num(r[3]), "press": num(r[4]),
               "openDoors": int(doors.group(1)),
               "openLocked": int(doors.group(2)) if doors.group(2) else None,
               "bendBars": num(r[6])}
        if r[0].startswith("18/"):
            p = r[0][3:]
            lo, hi = (100, 100) if p == "00" else score_range(p)
            str_exc.append({"min": lo, "max": hi, **row})
        else:
            lo, hi = score_range(r[0])
            str_rows.append({"min": lo, "max": hi, **row})
    out["str"], out["strExceptional"] = str_rows, str_exc

    out["dex"] = [{"min": a, "max": b, "reaction": num(r[1]), "missile": num(r[2]), "ac": num(r[3])}
                  for r in first_table(wiki["dex"]) for a, b in [score_range(r[0])]]

    con = []
    for r in first_table(wiki["con"]):
        a, b = score_range(r[0])
        hp = re.match(r"([+-]?\d+)(?:\(([+-]?\d+)\))?", r[1])
        regen = re.match(r"(\d+)/(\d+)", r[5])
        con.append({"min": a, "max": b, "hp": int(hp.group(1)),
                    "warrior": int(hp.group(2) or hp.group(1)),
                    "systemShock": num(r[2]), "resurrection": num(r[3]), "poison": num(r[4]),
                    "regen": {"hp": int(regen.group(1)), "turns": int(regen.group(2))} if regen else None})
    out["con"] = con

    out["int"] = [{"min": a, "max": b, "languages": num(r[1]), "maxSpellLevel": ordinal(r[2]),
                   "learnSpell": None if r[3] == "—" else num(r[3]),
                   "maxSpells": None if r[4] == "—" else ("all" if r[4] == "All" else num(r[4])),
                   "illusionImmunity": ordinal(r[5])}
                  for r in first_table(wiki["int"]) for a, b in [score_range(r[0])]]

    out["wis"] = [{"min": a, "max": b, "magicDef": num(r[1]),
                   "bonusSpells": [ordinal(x) for x in r[2].split(",") if ordinal(x)],
                   "spellFailure": num(r[3]),
                   "immunity": [] if r[4] == "—" else [x.strip() for x in r[4].split(",")]}
                  for r in first_table(wiki["wis"]) for a, b in [score_range(r[0])]]

    out["cha"] = [{"min": a, "max": b, "henchmen": num(r[1]), "loyalty": num(r[2]), "reaction": num(r[3])}
                  for r in first_table(wiki["cha"]) for a, b in [score_range(r[0])]]
    return src, out


if __name__ == "__main__":
    src, tables = build()
    lines = ["/**",
             " * GENERATED by tools/build-ability-tables.py - do not edit by hand.",
             " * Numeric data from the AD&D 2e fandom wiki ability tables (PHB Tables 1-6), as a",
             " * starter set for testing. Verify against an owned Player's Handbook.",
             " * Sources:"]
    lines += [f" *   {k}: {v['page']} (revision {v['revid']})" for k, v in src.items()]
    lines += [" */", "export const ABILITY_TABLES = " + json.dumps(tables, indent=2) + ";", ""]
    open("module/rules/ability-tables.mjs", "w").write("\n".join(lines))
    print("wrote module/rules/ability-tables.mjs:", {k: len(v) for k, v in tables.items()})
