#!/usr/bin/env python3
"""Generate module/rules/light-tables.mjs: light sources and dungeon turns (module/lights.mjs, module/dungeon-turns.mjs).

Sources (AD&D 2e fandom wiki, MediaWiki API):
  - "Vision and Light (PHB)": Table 63 Light Sources (radius, burning time) parsed; the beam widths of the beacon and
    bullseye lanterns regex-checked (they give the cone angle for token light).
  - "Time and Movement (PHB)": "A turn is equal to 10 minutes of game time." (regex-checked).
Curated: `ITEMS` (Table 63 source -> equipment identifier of "Equipment (PHB)"), checked against the pack sources.
Implementation choices: one flask of lamp oil is one pint; a candle without a length set is 6 inches long.
Run from the repo root (after build-equipment-data.py):  python3 tools/build-light-tables.py
"""
import glob
import importlib.util
import json
import math
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)
_tspec = importlib.util.spec_from_file_location("travel", "tools/build-travel-tables.py")
travel = importlib.util.module_from_spec(_tspec)
_tspec.loader.exec_module(travel)
need = travel.need

ITEMS = {"Torch": "torch", "Candle": "candle", "Hooded lantern": "lantern-hooded", "Bullseye lantern": "lantern-bullseye",
         "Beacon lantern": "lantern-beacon"}
OIL = "oil-lamp-per-flask"
PINTS_PER_FLASK = 1
CANDLE_INCHES = 6


def rows(wiki):
    t = wiki[wiki.index("Table 63: Light Sources"):]
    t = t[:t.index("|}")]
    out = []
    for block in t.split("|-")[1:]:
        cells = [re.sub(r"\s+", " ", x.replace("&nbsp;", " ")).strip() for x in re.findall(r"^\|\s*(.*)$", block, re.M)]
        if len(cells) == 3:
            out.append(cells)
    return out


def minutes(text):
    """Burning time text -> (minutes, unit) for the sources the system burns down."""
    m = re.fullmatch(r"(\d+) (min|hrs?)\.(?:/(pint|inch))?", text)
    if not m:
        return None
    n = int(m.group(1)) * (60 if m.group(2).startswith("hr") else 1)
    return n, m.group(3) or "item"


def main():
    w, rev, _ = classdata.page("Vision and Light (PHB)")
    t = re.sub(r"\s+", " ", w)
    beacon = int(need(t, r"the cone of light from a beacon lantern is (\d+) feet wide", "beacon beam").group(1))
    bullseye = int(need(t, r"A bullseye lantern has a beam (\d+) feet wide at its far end", "bullseye beam").group(1))
    tw, trev, _ = classdata.page("Time and Movement (PHB)")
    need(re.sub(r"\s+", " ", tw), r"A turn is equal to 10 minutes of game time", "turn length")
    ids = {json.load(open(f))["system"]["identifier"] for f in glob.glob("packs/_source/equipment/*.json")
           if not f.split("/")[-1].startswith("_folder")}
    assert OIL in ids and set(ITEMS.values()) <= ids, set(ITEMS.values()) - ids
    sources = {}
    for name, radius, burn in rows(w):
        cone = radius.endswith("*")
        r = int(re.match(r"(\d+) ft", radius).group(1))
        if name not in ITEMS:
            continue
        mins, unit = minutes(burn)
        assert mins % 10 == 0, (name, burn)
        spec = {"name": name, "radius": r, "burn": burn, "turns": mins // 10, "per": unit}
        if cone:
            width = beacon if name.startswith("Beacon") else bullseye
            spec["angle"] = round(2 * math.degrees(math.atan((width / 2) / r)))
        sources[ITEMS[name]] = spec
    assert sources["torch"] == {"name": "Torch", "radius": 15, "burn": "30 min.", "turns": 3, "per": "item"}, sources["torch"]
    assert sources["lantern-hooded"]["turns"] == 12 and sources["lantern-hooded"]["per"] == "pint", sources["lantern-hooded"]
    assert sources["candle"]["per"] == "inch" and sources["lantern-beacon"]["turns"] == 180, sources
    data = {"turnSeconds": 600, "sources": sources, "oil": OIL, "pintsPerFlask": PINTS_PER_FLASK, "candleInches": CANDLE_INCHES,
            "urls": {"table63": classdata.url("Vision and Light (PHB)"), "turn": classdata.url("Time and Movement (PHB)")}}
    with open("module/rules/light-tables.mjs", "w") as f:
        f.write("// GENERATED by tools/build-light-tables.py from the AD&D 2e fandom wiki (MediaWiki API): do not edit.\n")
        f.write(f"// Sources: Vision and Light (PHB) rev {rev} (Table 63), Time and Movement (PHB) rev {trev}.\n")
        f.write(f"export const LIGHT_TABLES = {json.dumps(data, ensure_ascii=False)};\n")
    print({k: (v["radius"], v["turns"], v["per"], v.get("angle")) for k, v in sources.items()})


if __name__ == "__main__":
    main()
