#!/usr/bin/env python3
"""Generate module/rules/encounter-tables.mjs: DMG Table 57 Surprise Modifiers.

Source (AD&D 2e fandom wiki, MediaWiki API): "Surprise (DMG)" Table 57 (modifiers to the group's surprise roll, by
what the other party is, what the PC party is, and conditions; "Camouflaged" is a range, -1 to -3). The roll itself is
1d10, surprised on 1-3 ("The Surprise Roll (PHB)"); a plus makes the roller less likely to be surprised.
Run from the repo root:  python3 tools/build-encounter-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

SECTIONS = {"Other Party is:": "other", "PC Party is:": "party", "Conditions are:": "conditions"}

if __name__ == "__main__":
    wiki, rev, _ = classdata.page("Surprise (DMG)")
    t = wiki[wiki.index("Table 57: Surprise Modifiers"):]
    t = t[:t.index("|}")]
    rows, section = [], None
    for chunk in re.split(r"\n\|-", t):
        lines = [l.strip() for l in chunk.strip().split("\n") if l.strip()]
        head = [l.lstrip("!").strip() for l in lines if l.startswith("!")]
        cells = [l.lstrip("|").strip() for l in lines if l.startswith("|") and not l.startswith("|+")]
        if head and head[0] in SECTIONS:
            section = SECTIONS[head[0]]
            continue
        if section and len(cells) == 2:
            label = re.sub(r"\*+$", "", cells[0]).strip()
            nums = [int(x) for x in re.findall(r"[+-]?\d+", cells[1].replace("−", "-"))]
            key = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")
            rows.append({"key": key, "group": section, "label": label, "values": nums if len(nums) == 1 else list(range(nums[0], nums[1] - 1, -1))})
    assert len(rows) == 14 and rows[0] == {"key": "silenced", "group": "other", "label": "Silenced", "values": [-2]}, rows[:2]
    assert any(r["key"] == "camouflaged" and r["values"] == [-1, -2, -3] for r in rows), rows
    data = {"surprisedOn": 3, "die": "1d10", "modifiers": rows}
    lines = ["/**",
             " * GENERATED by tools/build-encounter-tables.py - do not edit by hand.",
             f" *   Table 57 Surprise Modifiers: {classdata.url('Surprise (DMG)')} (revision {rev}); roll 1d10, surprised on 1-3",
             f" *   ({classdata.url('The Surprise Roll (PHB)')}).",
             " */",
             "export const ENCOUNTER_TABLES = " + json.dumps(data) + ";", ""]
    open("module/rules/encounter-tables.mjs", "w").write("\n".join(lines))
    print("wrote module/rules/encounter-tables.mjs:", [(r["group"], r["key"], r["values"]) for r in rows])
