#!/usr/bin/env python3
"""Generate module/rules/station-tables.mjs: Al-Qadim station (module/station.mjs).

Source (AD&D 2e fandom wiki, MediaWiki API): "Station in Life (AA)": Table 1 (initial station by kit, and the other
roles of NPCs) parsed; the rules used by the system regex-checked (multi- and dual-class, experience, spending,
crimes, poverty, slavery, reaction rolls, station checks).
Curated: `ALIAS` (Table 1 names whose kit identifier is not their slug), checked against packs/_source/kits.
Run from the repo root (after build-class-data.py):  python3 tools/build-station-tables.py
"""
import glob
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)
_tspec = importlib.util.spec_from_file_location("travel", "tools/build-travel-tables.py")
travel = importlib.util.module_from_spec(_tspec)
_tspec.loader.exec_module(travel)
need = travel.need

PAGE = "Station in Life (AA)"
ALIAS = {"Corsair": "corsair-al-qadim", "Beggar-thief": "beggar-thief-al-qadim", "Mystic": "mystic-al-qadim"}
RULES = {
    "multi": r"Multi-class characters use the lower of their two stations",
    "dual": r"Characters who become dual-class must halve their station upon taking the second role",
    "level": r"As soon as a character's experience level exceeds his or her initial station, the station improves to equal the experience level",
    "levelLoss": r"If characters should lose experience levels, their station drops accordingly, to a minimum equaling their original position",
    "money": r"For every 1,000 gold pieces spent each month in parties, gifts, sumptuous clothes, and other impressive displays, an individual's station is increased by 1 point",
    "criminal": r"Initial station is lost, replaced with a level of just 1 or 2 \(1d2\)",
    "penniless": r"Characters reduced to begging have a station of 3 immediately",
    "pennilessEnd": r"The penniless condition is reversed once such a .nouveau pauper. has cleared all outstanding bills or loans and has money equaling (500) gp per level\. Then former station is returned",
    "slave": r"Owner's station minus 1d6, or own station.whichever is lower",
    "freed": r"regain 1 point of station each month until they attain their former levels",
    "reaction": r"Individuals of higher station may modify the die roll 1 point in their favor for every 2 full points of difference in station",
    "check": r"Individuals whose station is 10 or less must receive a result less than their station to succeed\. Characters with a station of 11 or higher must receive a result higher than their station",
    "range": r"station is measured by a rating from 0 to 20",
}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    w, rev, _ = classdata.page(PAGE)
    t = re.sub(r"\s+", " ", w.replace("&mdash;", "—"))
    found = {key: need(t, pattern, key) for key, pattern in RULES.items()}
    assert found["pennilessEnd"].group(1) == "500", found["pennilessEnd"].group(0)
    table = w[w.index("Table 1: Station"):]
    table = table[:table.index("\n|}")]
    kit_ids = {json.load(open(f)).get("system", {}).get("identifier") for f in glob.glob("packs/_source/kits/*.json")}
    kits, npcs, section = {}, [], None
    for line in table.split("\n"):
        h = re.match(r'!\s*colspan="2"\s*\|\s*(.+)', line)
        if h:
            section = h.group(1).strip()
            continue
        m = re.match(r'\|\s*style="[^"]*"\s*\|\s*(.+?)\s*\|\|\s*(.+)$', line)
        if not m:
            continue
        name = re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", m.group(1)).strip()
        value = m.group(2).strip()
        if section.startswith("Other Roles"):
            formula = value if re.fullmatch(r"\d+d\d+(?: [+-] \d+)?", value) else None
            npcs.append({"name": name, "formula": formula, "text": value})
            continue
        ident = ALIAS.get(name, slug(name))
        assert ident in kit_ids, (name, ident)
        assert re.fullmatch(r"\d+d\d+(?: \+ \d+)?", value), (name, value)
        kits[ident] = {"name": name, "formula": value, "group": section.split()[0].lower()}
    assert len(kits) == 25 and kits["askar"]["formula"] == "1d6 + 4" and kits["beggar-thief-al-qadim"]["formula"] == "1d3", kits
    assert npcs[0] == {"name": "Poor merchant", "formula": "2d4", "text": "2d4"} and len(npcs) == 15, npcs
    data = {"kits": kits, "npcs": npcs, "min": 0, "max": 20, "goldPerPoint": 1000, "monthDays": 30, "criminal": "1d2",
            "penniless": 3, "pennilessGpPerLevel": 500, "slave": "1d6", "url": classdata.url(PAGE)}
    with open("module/rules/station-tables.mjs", "w") as f:
        f.write("// GENERATED by tools/build-station-tables.py from the AD&D 2e fandom wiki (MediaWiki API): do not edit.\n")
        f.write(f"// Source: {PAGE} rev {rev} (Table 1 and the station rules, regex-checked).\n")
        f.write(f"export const STATION_TABLES = {json.dumps(data, ensure_ascii=False)};\n")
    print(len(kits), "kits,", len(npcs), "NPC roles,", sum(1 for n in npcs if n["formula"]), "with a plain formula")


if __name__ == "__main__":
    main()
