#!/usr/bin/env python3
"""Generate module/rules/armor-type-tables.mjs: PHB Table 52 Weapon Type vs. Armor Modifiers (optional rule).

Source (AD&D 2e fandom wiki, MediaWiki API): "Weapon Types vs. Armor Modifiers (PHB)". Regex-checked: the modifiers are
"applied to the attacker's THAC0"; "The bonuses of magical armor do not change the type of armor"; "The modifiers are
not used when attacking creatures with a natural Armor Class"; a weapon of several types uses "the mode most favorable to
the attacker"; footnotes: chain mail "Includes bronze plate mail", leather armour "Includes padded armor and hides".
Rows map to the armour item identifiers of packs/_source/armor (asserted to exist).
Run from the repo root:  python3 tools/build-armor-type-tables.py
"""
import importlib.util
import json
import os
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

PAGE = "Weapon Types vs. Armor Modifiers (PHB)"
ROWS = {"Banded mail": ["banded-mail"], "Brigandine": ["brigandine"], "Chain mail": ["chain-mail", "bronze-plate-mail"],
        "Field Plate": ["field-plate"], "Full Plate": ["full-plate"], "Leather armor": ["leather", "padded", "hide"],
        "Plate mail": ["plate-mail"], "Ring mail": ["ring-mail"], "Scale mail": ["scale-mail"], "Splint mail": ["splint-mail"],
        "Studded leather": ["studded-leather"]}


def need(text, pattern, what):
    assert re.search(pattern, text), f"rule changed: {what}"


def build():
    wiki, rev, _ = classdata.page(PAGE)
    flat = re.sub(r"\s+", " ", wiki)
    need(flat, r"weapon vs\. armor modifiers applied to the attacker's THAC0", "THAC0")
    need(flat, r"The bonuses of magical armor do not change the type of armor", "magical armour")
    need(flat, r"The modifiers are not used when attacking creatures with a natural Armor Class", "natural AC")
    need(flat, r"the mode most favorable to the attacker can be used", "several types")
    need(flat, r"<nowiki>\*</nowiki> Includes bronze plate mail", "bronze plate")
    need(flat, r"<nowiki>\*\*</nowiki> Includes padded armor and hides", "padded, hides")
    table = {}
    for cells in classdata.table_rows(wiki, "Table 52"):
        if len(cells) != 4 or not re.fullmatch(r"-?\d+", cells[1]):
            continue
        name = cells[0].rstrip("*").strip()
        mods = {"S": int(cells[1]), "P": int(cells[2]), "B": int(cells[3])}
        for ident in ROWS[name]:
            assert os.path.exists(f"packs/_source/armor/{ident}.json"), ident
            table[ident] = {"row": name, **mods}
    assert len(table) == sum(len(v) for v in ROWS.values()), sorted(table)
    assert table["full-plate"] == {"row": "Full Plate", "S": 4, "P": 3, "B": 0} and table["chain-mail"]["B"] == -2
    return {"table": table, "url": classdata.url(PAGE)}, rev


if __name__ == "__main__":
    data, rev = build()
    with open("module/rules/armor-type-tables.mjs", "w") as f:
        f.write("// GENERATED by tools/build-armor-type-tables.py from the AD&D 2e fandom wiki (MediaWiki API): do not edit.\n")
        f.write(f"// Source: {PAGE} (revision {rev}), Table 52 (values are added to the attacker's THAC0).\n")
        f.write(f"export const ARMOR_TYPES = {json.dumps(data, ensure_ascii=False)};\n")
    print(len(data["table"]), "armour identifiers")
