#!/usr/bin/env python3
"""Generate module/rules/movement-tables.mjs: encumbrance and movement.

Sources (AD&D 2e fandom wiki, MediaWiki API):
  * Table 47: Character Encumbrance and Table 48: Modified Movement Rates ("Encumbrance Tables (PHB)").
  * Table 64: Base Movement Rates ("Movement (PHB)"); also read by build-race-data.py for the race items.
Strength rows are keyed on a single scale: score * 100 + exceptional percentile (18/01 = 1801, 18/00 = 1900).
Run from the repo root:  python3 tools/build-movement-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)


def str_range(label):
    """'4-5' -> (400, 500); '18' -> (1800, 1800); '18/01-50' -> (1801, 1850); '18/00' -> (1900, 1900)."""
    label = label.strip()
    m = re.fullmatch(r"18/(\d\d)(?:-(\d\d))?", label)
    if m:
        lo = int(m.group(1)) or 100
        hi = int(m.group(2) or m.group(1)) or 100
        return 1800 + lo, 1800 + hi
    a, _, b = label.partition("-")
    return int(a) * 100, int(b or a) * 100


def rows_of(table):
    out = []
    for chunk in re.split(r"\n\|-", table)[1:]:
        cells = [l[1:].strip() for l in chunk.strip().split("\n") if l.startswith("|") and not l.startswith(("|+", "|}"))]
        if cells:
            out.append(cells)
    return out


def section(wiki, caption):
    t = wiki[wiki.index(caption):]
    return t[:t.index("|}")]


def build_encumbrance():
    wiki, rev, _ = classdata.page("Encumbrance Tables (PHB)")
    t47 = []
    for cells in rows_of(section(wiki, "Table 47: Character Encumbrance")):
        lo, hi = str_range(cells[0])
        # upper bound of each category column (Unencumbered, Light, Moderate, Heavy, Severe)
        limits = [int(c.split("-")[-1]) for c in cells[1:6]]
        t47.append({"min": lo, "max": hi, "limits": limits, "maxCarried": int(cells[6])})
    t48_text = section(wiki, "Table 48: Modified Movement Rates")
    headers = [[int(x) for x in re.findall(r"^!\s*(\d+)\s*$", block, re.M)]
               for block in re.split(r"\n\|-", t48_text)[1:3]]
    t48 = []
    for cells in rows_of(t48_text):
        if not re.match(r"\d", cells[0]):
            continue
        lo, hi = str_range(cells[0])
        t48.append({"min": lo, "max": hi, "loads": [int(c) if c.isdigit() else None for c in cells[1:13]]})
    assert len(t47) == 16 and len(t48) == 16, (len(t47), len(t48))
    assert headers[0] == list(range(12, 0, -1)) and len(headers[1]) == 12, headers
    # Table 48's 1-movement column is the most a character can carry (Table 47 Max. Carried) or less.
    for a, b in zip(t47, t48):
        assert (a["min"], a["max"]) == (b["min"], b["max"])
    return t47, {"rates12": headers[0], "rates6": headers[1], "rows": t48}, rev


def build_base_move():
    wiki, rev, _ = classdata.page("Movement (PHB)")
    t = section(wiki, "Table 64: Base Movement Rates")
    move = {}
    for cells in rows_of(t):
        if len(cells) == 2 and cells[1].isdigit():
            move[re.sub(r"[^a-z]+", "-", cells[0].lower()).strip("-")] = int(cells[1])
    assert set(move) == {"human", "dwarf", "elf", "half-elf", "gnome", "halfling"}, move
    return move, rev


if __name__ == "__main__":
    t47, t48, rev_enc = build_encumbrance()
    move, rev_move = build_base_move()
    lines = ["/**",
             " * GENERATED by tools/build-movement-tables.py - do not edit by hand.",
             f" * PHB Tables 47 and 48: {classdata.url('Encumbrance Tables (PHB)')} (revision {rev_enc})",
             f" * PHB Table 64: {classdata.url('Movement (PHB)')} (revision {rev_move})",
             " * Strength key: score * 100 + exceptional percentile (18/01 = 1801, 18/00 = 1900).",
             " */",
             "/** Table 47: upper weight (lb) of Unencumbered, Light, Moderate, Heavy, Severe; most weight that can be carried. */",
             "export const ENCUMBRANCE_TABLE = " + json.dumps(t47) + ";", "",
             "/** Table 48: per Strength, the most weight (lb) for each modified movement rate (rates12 / rates6 by base move). */",
             "export const MOVEMENT_TABLE = " + json.dumps(t48) + ";", "",
             "/** Table 64: base movement rate per race identifier. */",
             "export const BASE_MOVEMENT = " + json.dumps(move) + ";", ""]
    open("module/rules/movement-tables.mjs", "w").write("\n".join(lines))
    print("wrote module/rules/movement-tables.mjs:", len(t47), "Table 47 rows,", len(t48["rows"]), "Table 48 rows,", move)
