#!/usr/bin/env python3
"""Generate module/rules/spell-tables.mjs (spell progressions) and the example spell Items (packs/_source/spells).

Sources (AD&D 2e fandom wiki, MediaWiki API):
  * Table 21: Wizard Spell Progression ("Wizard Tables (PHB)"); Table 24: Priest Spell Progression ("Priest Tables
    (PHB)", footnotes: 6th level "Usable only by priests with 17 or greater Wisdom", 7th "18 or greater"); Table 17:
    Paladin and Ranger Spell Progression ("Warrior Tables (PHB)", with casting level); Table 32: Bard Spell
    Progression ("Rogue Tables (PHB)").
  * EXAMPLES: a few Player's Handbook spell pages, converted by module/importers/adnd2e-wiki.mjs (the parser the
    in-world spell importer uses), so the examples and imported spells come out the same. Mechanics and a link
    only; the spell descriptions are not copied.
Run from the repo root (needs node):  python3 tools/build-spell-data.py
"""
import importlib.util
import json
import os
import re
import subprocess
import tempfile
import urllib.parse
import urllib.request

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

EXAMPLES = ["Magic Missile (Wizard Spell)", "Sleep (Wizard Spell)", "Detect Magic (Wizard Spell)", "Web (Wizard Spell)",
            "Fireball (Wizard Spell)", "Lightning Bolt (Wizard Spell)",
            "Cure Light Wounds (Priest Spell)", "Bless (Priest Spell)", "Command (Priest Spell)",
            "Hold Person (Priest Spell)", "Spiritual Hammer (Priest Spell)", "Cure Disease (Priest Spell)"]


def api(**p):
    p["format"] = "json"
    req = urllib.request.Request(classdata.API + "?" + urllib.parse.urlencode(p), headers=classdata.UA)
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def table_rows(wiki, caption):
    """Data rows of the table with this caption: cells split on '||' or one per line; '—' -> 0; '9*' -> 9."""
    i = wiki.index(caption)
    t = wiki[i:wiki.index("|}", i)]
    rows = []
    for chunk in re.split(r"\n\|-", t)[1:]:
        lines = [l.strip() for l in chunk.strip().split("\n") if l.strip().startswith("|") and not l.strip().startswith(("|+", "|}"))]
        cells = [c.strip() for l in lines for c in l[1:].split("||")]
        if cells and re.match(r"\d", cells[0]):
            rows.append([0 if c in ("—", "-", "") else int(re.match(r"\d+", c).group()) if re.match(r"\d", c) else c for c in cells])
    return rows


def progression(title, caption, first_level, skip=1, casting=False):
    """{level: {casting, slots: [per spell level]}}; `skip` leading non-slot columns after the level."""
    wiki, rev, _ = classdata.page(title)
    out = {}
    for r in table_rows(wiki, caption):
        lvl = r[0]
        out[lvl] = {"casting": r[skip] if casting else lvl, "slots": [c for c in r[skip + (1 if casting else 0):] if isinstance(c, int)]}
    assert min(out) == first_level, (caption, sorted(out))
    return out, rev


if __name__ == "__main__":
    wizard, rev21 = progression("Wizard Tables (PHB)", "|+ Table 21: Wizard Spell Progression", 1)
    priest, rev24 = progression("Priest Tables (PHB)", "|+ Table 24: Priest Spell Progression", 1)
    paladin, rev17 = progression("Warrior Tables (PHB)", "|+ Table 17: Paladin Spell Progression", 9, casting=True)
    ranger, _ = progression("Warrior Tables (PHB)", "|+ Table 17: Ranger Spell Progression", 1, skip=3, casting=True)
    ranger = {k: v for k, v in ranger.items() if any(v["slots"])}  # rangers cast from 8th level
    bard, rev32 = progression("Rogue Tables (PHB)", "|+ Table 32: Bard Spell Progression", 1)
    assert sorted(wizard) == list(range(1, 21)) and all(len(v["slots"]) == 9 for v in wizard.values()), wizard
    assert sorted(priest) == list(range(1, 21)) and all(len(v["slots"]) == 7 for v in priest.values()), priest
    assert sorted(paladin) == list(range(9, 21)) and all(len(v["slots"]) == 4 for v in paladin.values()), paladin
    assert min(ranger) == 8 and all(len(v["slots"]) == 3 for v in ranger.values()), ranger
    assert sorted(bard) == list(range(1, 21)) and all(len(v["slots"]) == 6 for v in bard.values()), bard
    assert wizard[1]["slots"][0] == 1 and priest[1]["slots"][0] == 1 and paladin[9] == {"casting": 1, "slots": [1, 0, 0, 0]}
    tables = {"wizard": wizard, "priest": priest, "paladin": paladin, "ranger": ranger, "bard": bard}
    lines = ["/**",
             " * GENERATED by tools/build-spell-data.py - do not edit by hand.",
             " * Spell progressions per caster table and class level: { casting level, slots per spell level (index 0 = 1st) }.",
             f" *   Table 21 (wizard) {classdata.url('Wizard Tables (PHB)')} rev {rev21}",
             f" *   Table 24 (priest) {classdata.url('Priest Tables (PHB)')} rev {rev24}: 6th-level spells need Wisdom 17+, 7th 18+",
             f" *   Table 17 (paladin, ranger) {classdata.url('Warrior Tables (PHB)')} rev {rev17}",
             f" *   Table 32 (bard) {classdata.url('Rogue Tables (PHB)')} rev {rev32}",
             " */",
             "export const SPELL_PROGRESSION = " + json.dumps(tables) + ";", ""]
    open("module/rules/spell-tables.mjs", "w").write("\n".join(lines))

    r = api(action="query", prop="revisions|categories", rvprop="content|ids", rvslots="main", cllimit=500, titles="|".join(EXAMPLES))
    raw = [{"title": p["title"], "wiki": p["revisions"][0]["slots"]["main"]["*"], "revid": p["revisions"][0]["revid"],
            "categories": [c["title"].replace("Category:", "") for c in p.get("categories", [])]}
           for p in r["query"]["pages"].values() if "revisions" in p]
    assert len(raw) == len(EXAMPLES), sorted(set(EXAMPLES) - {x["title"] for x in raw})
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        json.dump(raw, f)
    try:
        out = subprocess.run(["node", "tools/spell-items.mjs", f.name], check=True, capture_output=True, text=True).stdout
    finally:
        os.unlink(f.name)
    items = json.loads(out)
    assert len(items) == len(EXAMPLES), [x["title"] for x in raw]
    # Damage and healing options are read from each page by module/importers/spell-damage.mjs (no per-spell data).
    dmg = {it["name"]: [d["formula"] for d in it["system"]["damage"]] for it in items}
    assert dmg["Fireball"] == ["(min(@level, 10))d6"] and dmg["Lightning Bolt"] == ["(min(@level, 10))d6"], dmg
    assert dmg["Magic Missile"] == ["1d4 + 1"] and dmg["Cure Light Wounds"] == ["1d8", "1d8"], dmg
    # Folders by class, then spell level (the same layout the spell importer uses in the world).
    tops = {k: classdata.folder_doc(f"spells.{k}", label, sort=i * 1000)
            for i, (k, label) in enumerate([("wizard", "Wizard Spells"), ("priest", "Priest Spells")])}
    folders, docs = {}, list(tops.values())
    for it in items:
        key = (it["system"]["kind"], it["system"]["level"])
        if key not in folders:
            name = "Cantrips / orisons" if key[1] == 0 else f"Level {key[1]}"
            folders[key] = classdata.folder_doc(f"spells.{key[0]}.{key[1]}", name, parent=tops[key[0]]["_id"], sort=key[1] * 100)
            docs.append(folders[key])
    for i, it in enumerate(sorted(items, key=lambda d: (d["system"]["kind"], d["system"]["level"], d["name"]))):
        doc = classdata.item_doc("spell", "s." + it["system"]["identifier"], it["name"], it["img"], it["system"], i * 100)
        doc["folder"] = folders[(it["system"]["kind"], it["system"]["level"])]["_id"]
        doc["flags"] = it["flags"]
        docs.append(doc)
    classdata.write_docs("packs/_source/spells", docs)
    print("wrote module/rules/spell-tables.mjs and packs/_source/spells:",
          [(d["name"], d["system"]["kind"], d["system"]["level"]) for d in docs if "system" in d])
