#!/usr/bin/env python3
"""Generate module/rules/encounter-tables.mjs: DMG Table 57 Surprise Modifiers and DMG Table 59 Encounter Reactions.

Source (AD&D 2e fandom wiki, MediaWiki API): "Surprise (DMG)" Table 57 (modifiers to the group's surprise roll, by
what the other party is, what the PC party is, and conditions; "Camouflaged" is a range, -1 to -3). The roll itself is
1d10, surprised on 1-3 ("The Surprise Roll (PHB)"); a plus makes the roller less likely to be surprised.
Table 59 ("Encounter Reactions (DMG)"): 2d10, modified, read in the column matching the player characters' behaviour
(friendly, indifferent, threatening, hostile); rows "2 or less" to "20" (a total above 20 reads as 20).
Run from the repo root:  python3 tools/build-encounter-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

SECTIONS = {"Other Party is:": "other", "PC Party is:": "party", "Conditions are:": "conditions"}

COLUMNS = ["friendly", "indifferent", "threatening", "hostile"]
RESULTS = {"Flight": "flight", "Friendly": "friendly", "Indifferent": "indifferent", "Cautious": "cautious",
           "Threatening": "threatening", "Hostile": "hostile"}
REACTION_REV = {}


def reactions():
    """DMG Table 59: [{min, max, friendly, indifferent, threatening, hostile}] (min null for "2 or less")."""
    wiki, rev, _ = classdata.page("Encounter Reactions (DMG)")
    REACTION_REV["rev"] = rev
    assert re.search(r"roll 2d10 and add the numbers on the two dice", wiki), "Table 59: 2d10 sentence not found"
    t = wiki[wiki.index("Table 59: Encounter Reactions"):]
    t = t[:t.index("|}")]
    head = re.findall(r"^!\s*(Friendly|Indifferent|Threatening|Hostile)\s*$", t, re.M)
    assert [h.lower() for h in head] == COLUMNS, head
    out = []
    for chunk in re.split(r"\n\|-", t)[1:]:
        cells = [l.lstrip("|").strip() for l in chunk.strip().split("\n") if l.startswith("|") and not l.startswith("|+")]
        if len(cells) != 5:
            continue
        roll = cells[0]
        m = re.fullmatch(r"(\d+) or less", roll)
        lo, hi = (None, int(m.group(1))) if m else (int(roll), int(roll))
        out.append({"min": lo, "max": hi, **{c: RESULTS[v] for c, v in zip(COLUMNS, cells[1:])}})
    assert len(out) == 19 and out[0]["min"] is None and out[0]["max"] == 2 and out[-1]["min"] == 20, out
    assert out[0]["hostile"] == "flight" and out[-1]["friendly"] == "hostile", out
    out[-1]["max"] = None  # 20 or more
    return out


if __name__ == "__main__":
    wiki, rev, _ = classdata.page("Surprise (DMG)")
    t = wiki[wiki.index("Table 57: Surprise Modifiers"):]
    t = t[:t.index("|}")]
    rows, section = [], None
    for chunk in re.split(r"\n\|-", t):
        lines = [l.strip() for l in chunk.strip().split("\n") if l.strip()]
        head = [l.lstrip("!").strip() for l in lines if l.startswith("!")]
        cells = [l.lstrip("|").strip() for l in lines if l.startswith("|") and not l.startswith("|+")]
        if head and head[0] in SECTIONS:
            section = SECTIONS[head[0]]
            continue
        if section and len(cells) == 2:
            label = re.sub(r"\*+$", "", cells[0]).strip()
            nums = [int(x) for x in re.findall(r"[+-]?\d+", cells[1].replace("−", "-"))]
            key = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")
            rows.append({"key": key, "group": section, "label": label, "values": nums if len(nums) == 1 else list(range(nums[0], nums[1] - 1, -1))})
    assert len(rows) == 14 and rows[0] == {"key": "silenced", "group": "other", "label": "Silenced", "values": [-2]}, rows[:2]
    assert any(r["key"] == "camouflaged" and r["values"] == [-1, -2, -3] for r in rows), rows
    data = {"surprisedOn": 3, "die": "1d10", "modifiers": rows, "reactions": reactions()}
    lines = ["/**",
             " * GENERATED by tools/build-encounter-tables.py - do not edit by hand.",
             f" *   Table 57 Surprise Modifiers: {classdata.url('Surprise (DMG)')} (revision {rev}); roll 1d10, surprised on 1-3",
             f" *   ({classdata.url('The Surprise Roll (PHB)')}).",
             f" *   Table 59 Encounter Reactions: {classdata.url('Encounter Reactions (DMG)')} (revision {REACTION_REV['rev']}); 2d10.",
             " */",
             "export const ENCOUNTER_TABLES = " + json.dumps(data) + ";", ""]
    open("module/rules/encounter-tables.mjs", "w").write("\n".join(lines))
    print("wrote module/rules/encounter-tables.mjs:", [(r["group"], r["key"], r["values"]) for r in rows])
