#!/usr/bin/env python3
"""Generate module/rules/province-tables.mjs: the elemental province of wizard spells (Al-Qadim).

Source (AD&D 2e fandom wiki, MediaWiki API): "Appendix A: Wizard Spells by Province (AA)" (Arabian Adventures): for
each spell level, lists headed Universal, Flame, Sand, Sea and Wind; a spell under a province belongs to it (a few
are in two, e.g. Wall of Fog: sea and wind). Universal spells have no province. Keyed by the linked page title.
Used by the spell importer (spell `system.provinces`) and the elemental mage kit ("+1 to each damage die inflicted with
an attack using that element", Elemental Mage (Character Kit)).
Run from the repo root:  python3 tools/build-province-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

PAGE = "Appendix A: Wizard Spells by Province (AA)"
PROVINCES = {"Flame": "flame", "Sand": "sand", "Sea": "sea", "Wind": "wind"}

if __name__ == "__main__":
    wiki, rev, _ = classdata.page(PAGE)
    levels = re.findall(r"==(\d)(?:st|nd|rd|th)-level Spells==", wiki)
    assert levels == [str(n) for n in range(1, 10)], levels
    out = {}
    heading = None
    for line in wiki.split("\n"):
        h = re.match(r"^'''([A-Za-z]+)'''\s*$", line.strip())
        if h:
            heading = h.group(1)
            assert heading in PROVINCES or heading == "Universal", heading
            continue
        if line.startswith("=="):
            heading = None
            continue
        link = re.search(r"\[\[([^|\]]+)(?:\|[^\]]*)?\]\]", line)
        if link and line.startswith(":") and heading in PROVINCES:
            out.setdefault(link.group(1).strip(), [])
            if PROVINCES[heading] not in out[link.group(1).strip()]:
                out[link.group(1).strip()].append(PROVINCES[heading])
    assert out.get("Lightning Bolt (Wizard Spell)") is None and out.get("Burning Hands (Wizard Spell)") == ["flame"], out.get("Burning Hands (Wizard Spell)")
    assert out.get("Wall of Fog (Wizard Spell)") == ["sea", "wind"], out.get("Wall of Fog (Wizard Spell)")
    counts = {p: sum(p in v for v in out.values()) for p in PROVINCES.values()}
    open("module/rules/province-tables.mjs", "w").write("\n".join([
        "/**",
        " * GENERATED by tools/build-province-tables.py - do not edit by hand.",
        f" * {PAGE}: {classdata.url(PAGE)} (revision {rev}).",
        " * Wizard spell page title -> elemental provinces (flame, sand, sea, wind); universal spells are not listed.",
        " */",
        "export const SPELL_PROVINCES = " + json.dumps(dict(sorted(out.items())), ensure_ascii=False) + ";", ""]))
    print(f"wrote module/rules/province-tables.mjs: {len(out)} spells {counts} ({PAGE} rev {rev})")
