#!/usr/bin/env python3
"""Generate module/rules/aging-tables.mjs: PHB Table 11 (Age) and Table 12 (Aging Effects).

Sources (AD&D 2e fandom wiki, MediaWiki API): "Character Race Tables (PHB)" (Tables 11 and 12; the Table 12 footnotes
give each category's changes) and "Other Characteristics (PHB)" (regex-checked: the 18/xx Strength rule "loses 1 point of
Strength (or half of his exceptional Strength rating)" at middle age and "2 more points of Strength (or all his exceptional
Strength and 1 point more)" at old age; "All ageing adjustments are cumulative"; magical ageing changes the maximum age,
not the actual age). The elf footnote ("does not die" but migrates) is kept as a flag.
Run from the repo root:  python3 tools/build-aging-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

RACES = {"Dwarf": "dwarf", "Elf": "elf", "Gnome": "gnome", "Half-Elf": "half-elf", "Halfling": "halfling", "Human": "human"}
ABIL = {"Str": "str", "Dex": "dex", "Con": "con", "Int": "int", "Wis": "wis", "Cha": "cha"}
CATS = ["middle", "old", "venerable"]


def need(text, pattern, what):
    assert re.search(pattern, text), f"rule changed: {what}"


def rows(wiki, heading):
    t = wiki[wiki.index(f"=={heading}=="):]
    t = t[:t.index("\n|}")]
    out = []
    for chunk in re.split(r"\n\|-", t):
        cells = [c.lstrip("|").strip() for c in chunk.strip().split("\n") if c.startswith("|") and not c.startswith(("|+", "|}"))]
        if cells and re.match(r"\[\[", cells[0]):
            out.append([re.sub(r"\[\[([^\]|]+\|)?([^\]]+)\]\]", r"\2", c).strip() for c in cells])
    return out


def changes(text):
    """'-2 Str/Dex, -1 Con; +1 Wis' -> {str: -2, dex: -2, con: -1, wis: 1}."""
    out = {}
    for sign, n, abil in re.findall(r"([+-])(\d+) ([A-Za-z/]+)", text):
        for a in abil.split("/"):
            out[ABIL[a]] = int(n) * (1 if sign == "+" else -1)
    return out


def build():
    wiki, rev, _ = classdata.page("Character Race Tables (PHB)")
    age = {}
    for race, base, var, mx in rows(wiki, "Table 11: Age"):
        m = re.fullmatch(r"(\d+)\+(\d+d\d+)\*?", mx.replace(" ", ""))
        assert m and re.fullmatch(r"\d+d\d+", var), (race, var, mx)
        age[RACES[race]] = {"base": int(base), "variable": var, "maxBase": int(m.group(1)), "maxDice": m.group(2)}
    effects = {}
    for race, mid, old, ven in rows(wiki, "Table 12: Aging Effects"):
        effects[RACES[race]] = [int(re.match(r"\d+", x).group(0)) for x in (mid, old, ven)]
    assert list(age) == list(RACES.values()) == list(effects), (list(age), list(effects))
    notes = re.findall(r"<nowiki>(\*+)</nowiki> ([^{\n]+)", wiki[wiki.index("==Table 12"):wiki.index("==Table 13")])
    assert [n for n, _ in notes] == ["*", "**", "***"], notes
    cat = {c: changes(t) for c, (_, t) in zip(CATS, notes)}
    assert cat == {"middle": {"str": -1, "con": -1, "int": 1, "wis": 1}, "old": {"str": -2, "dex": -2, "con": -1, "wis": 1},
                   "venerable": {"str": -1, "dex": -1, "con": -1, "int": 1, "wis": 1}}, cat
    # Table 12 = 1/2, 2/3 and all of the base maximum (Table 11), checked per race (rounded as printed).
    for r, (mid, old, ven) in effects.items():
        b = age[r]["maxBase"]
        assert ven == b and abs(mid - b / 2) <= 0.5 and abs(old - b * 2 / 3) <= 0.5, (r, mid, old, ven, b)
    elf = re.search(r"Upon attaining this age, an elf does not die", wiki)
    assert elf, "elf note"
    ow, orev, _ = classdata.page("Other Characteristics (PHB)")
    flat = re.sub(r"\s+", " ", ow)
    need(flat, r"loses 1 point of Strength \(or half of his exceptional Strength rating\)", "middle-age 18/xx")
    need(flat, r"loses 2 more points of Strength \(or all his exceptional Strength and 1 point more\)", "old-age 18/xx")
    need(flat, r"All ageing adjustments are cumulative", "cumulative")
    need(flat, r"the actual age of the character is unaffected", "magical ageing")
    return {"age": age, "categories": effects, "changes": cat, "elfMigrates": "elf",
            "url": classdata.url("Character Race Tables (PHB)"), "textUrl": classdata.url("Other Characteristics (PHB)")}, rev, orev


if __name__ == "__main__":
    data, rev, orev = build()
    with open("module/rules/aging-tables.mjs", "w") as f:
        f.write("// GENERATED by tools/build-aging-tables.py from the AD&D 2e fandom wiki (MediaWiki API): do not edit.\n")
        f.write(f"// Sources: Character Race Tables (PHB) (revision {rev}), Tables 11 and 12; Other Characteristics (PHB) (revision {orev}).\n")
        f.write(f"export const AGING = {json.dumps(data, ensure_ascii=False)};\n")
    print(json.dumps(data["categories"]))
