#!/usr/bin/env python3
"""Generate module/rules/treasure-tables.mjs: magical item categories and gem classes (DMG).

Sources (AD&D 2e fandom wiki, MediaWiki API):
  * "Magical Item Tables (DMG)": Table 88 (category per DMG table). Armour, shields and weapons (Tables 105, 108) are
    left out: magical armour and weapons are armour and weapon items with a magical bonus.
  * "Treasure Tables (DMG)": Table 85 Gem Table (base value per class; uncut stones 10% of it) and Table 87 Objects of
    Art (value ranges).
Run from the repo root:  python3 tools/build-treasure-tables.py
"""
import importlib.util
import json
import re

_spec = importlib.util.spec_from_file_location("classdata", "tools/build-class-data.py")
classdata = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(classdata)

# Table 88 category -> item category key (the magical item `category` field).
CATEGORY_KEYS = {
    "Potions and Oils": "potion", "Scrolls": "scroll", "Rings": "ring", "Rods": "rod", "Staves": "staff", "Wands": "wand",
    "Miscellaneous Magic: Books and Tomes": "book", "Miscellaneous Magic: Jewels and Jewelry": "jewel",
    "Miscellaneous Magic: Cloaks and Robes": "cloak", "Miscellaneous Magic: Boots and Gloves": "boots",
    "Miscellaneous Magic: Girdles and Helms": "girdle", "Miscellaneous Magic: Bags and Bottles": "bag",
    "Miscellaneous Magic: Dusts and Stones": "dust", "Miscellaneous Magic: Household Items and Tools": "household",
    "Miscellaneous Magic: Musical Instruments": "instrument", "Miscellaneous Magic: The Weird Stuff": "weird",
}
SKIP = {"Armor and Shields", "Weapons"}
GEM_KEYS = {"Ornamental": "ornamental", "Semi-precious": "semiprecious", "Fancy": "fancy", "Precious": "precious",
            "Gems": "gem", "Jewels": "jewel"}


def table(wiki, caption):
    i = wiki.index(caption)
    return wiki[i:wiki.index("|}", i)]


def rows(t):
    out = []
    for chunk in re.split(r"\n\|-", t)[1:]:
        cells = [re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", l.lstrip("|!")).strip()
                 for l in chunk.strip().split("\n") if l.startswith("|") and not l.startswith(("|+", "|}"))]
        if cells:
            out.append(cells)
    return out


def gp(text):
    return int(text.replace(",", "").replace("gp", "").strip())


if __name__ == "__main__":
    mw, rev88, _ = classdata.page("Magical Item Tables (DMG)")
    categories = []
    for roll, cat in rows(table(mw, "Table 88: Magical Items")):
        m = re.match(r"Table (\d+): (.+)", cat)
        name = m.group(2).strip()
        if name in SKIP:
            continue
        categories.append({"key": CATEGORY_KEYS[name], "table": int(m.group(1)), "name": name})
    assert [c["table"] for c in categories] == list(range(89, 105)), categories

    tw, rev85, _ = classdata.page("Treasure Tables (DMG)")
    gems = [{"key": GEM_KEYS[r[2]], "name": r[2], "value": gp(r[1])} for r in rows(table(tw, "Table 85: Gem Table"))]
    assert [g["value"] for g in gems] == [10, 50, 100, 500, 1000, 5000], gems
    assert "base value reduced to 10%" in tw, "uncut stone rule changed"
    art = [[gp(x) for x in r[1].split("-")] for r in rows(table(tw, "Table 87: Objects of Art"))]
    assert art[0] == [10, 100] and art[-1] == [2000, 12000] and len(art) == 12, art

    data = {"magicCategories": categories, "gemClasses": gems, "uncutFactor": 0.1, "artValues": art}
    lines = ["/**",
             " * GENERATED by tools/build-treasure-tables.py - do not edit by hand.",
             f" *   Table 88 (magical item categories, DMG Tables 89-104): {classdata.url('Magical Item Tables (DMG)')} (revision {rev88})",
             f" *   Table 85 (gem base values; uncut stones 10%), Table 87 (objects of art): {classdata.url('Treasure Tables (DMG)')} (revision {rev85})",
             " */",
             "export const TREASURE_TABLES = " + json.dumps(data) + ";", ""]
    open("module/rules/treasure-tables.mjs", "w").write("\n".join(lines))
    print("wrote module/rules/treasure-tables.mjs:", [c["key"] for c in categories], [(g["key"], g["value"]) for g in gems])
